/**
 * 🌐 Template Localizer — تسليم القوالب بلغة المستخدم المختارة.
 *
 * المشكلة: القوالب مكتوبة بالعربية (lang/dir/نصوص) فتصل عربيةً لمن اختار
 * الإنجليزية. الحل الحتمي (لا LLM يبتر الملفات): قاموس مطابقة حرفية للسلاسل
 * الظاهرة للمستخدم يُطبَّق بالأطول-أولاً على HTML/JS + قلب lang/dir +
 * تصحيح توسيط الـ toast للاتجاه الجديد. التعليقات البرمجية تبقى كما هي إن لم
 * تطابق، والدوال لا تُمسّ إطلاقاً (استبدال نصّي داخل سلاسل عربية فقط).
 *
 * قاعدة صارمة: لا فواصل عليا (') في أي ترجمة — كي لا تكسر سلاسل JS المفردة.
 */

// [عربي, إنجليزي] — التغطية الكاملة لسلاسل القوالب الظاهرة (مرتّبة منطقياً؛
// الترتيب الفعلي عند التطبيق: بالأطول أولاً لمنع المطابقات الجزئية).
const DICT = [
    // ── عام/دخول/حسابات ─────────────────────────────────────────────
    ['العميل يتسوّق بلا تسجيل — هذا الدخول للإدارة فقط', 'Customers shop without signing in — this login is for management only'],
    ['الزائر يتصفّح بلا تسجيل — هذا الدخول للإدارة فقط', 'Visitors browse without signing in — this login is for management only'],
    ['ادخل بحسابك لتُوجَّه لصفحتك حسب دورك', 'Sign in and you will be routed to your page by role'],
    ['ادخل بحسابك لتُوجَّه لصفحتك', 'Sign in to be routed to your page'],
    ['سجّل لإتمام طلبك — دقائق فقط', 'Register to complete your order — it takes a minute'],
    ['سجّل لطلب رحلتك — دقائق فقط', 'Register to request your ride — it takes a minute'],
    ['سجّل لتبدأ التعلّم وحفظ تقدّمك', 'Register to start learning and save your progress'],
    ['سجّل لحفظ تذاكرك ومتابعتها', 'Register to save and track your tickets'],
    ['سجّل لحفظ حجوزاتك', 'Register to save your bookings'],
    ['سجّل لإكمال طلبك', 'Register to complete your order'],
    ['أدخل اسمك من فضلك', 'Please enter your name'],
    ['تم تسجيل الخروج', 'Signed out'],
    ['تسجيل الدخول', 'Sign in'],
    ['اسم المستخدم', 'Username'],
    ['كلمة المرور', 'Password'],
    ['بيانات غير صحيحة', 'Invalid credentials'],
    ['حسابات تجربة', 'Demo accounts'],
    ['حساب إدارة تجربة', 'Demo admin account'],
    ['إنشاء حساب عميل', 'Create customer account'],
    ['إنشاء حساب راكب', 'Create rider account'],
    ['إنشاء حساب مسافر', 'Create traveler account'],
    ['إنشاء حساب طالب', 'Create student account'],
    ['إنشاء حساب', 'Create account'],
    ['لديك حساب طاقم؟', 'Have a staff account?'],
    ['لديك حساب إدارة؟', 'Have an admin account?'],
    ['عميل جديد؟', 'New customer?'],
    ['راكب جديد؟', 'New rider?'],
    ['مسافر جديد؟', 'New traveler?'],
    ['طالب جديد؟', 'New student?'],
    ['مستخدم جديد؟', 'New user?'],
    ['تسجيل ومتابعة', 'Register and continue'],
    ['تسجيل وطلب الرحلة', 'Register and request ride'],
    ['تسجيل وبدء التعلّم', 'Register and start learning'],
    ['دخول الموظّف', 'Staff sign in'],
    ['دخول الطاقم', 'Staff sign in'],
    ['دخول المدير', 'Admin sign in'],
    ['تسجيل', 'Register'],
    ['تجريبي', 'Demo'],
    ['تجربة', 'Demo'],
    ['دخول', 'Sign in'],
    ['خروج', 'Sign out'],
    ['مرحباً', 'Welcome'],
    ['أهلاً', 'Hello'],

    // ── تجارة/سلة/طلبات ────────────────────────────────────────────
    ['منتجات مختارة بعناية، أسعار منافسة، وتوصيل سريع لبابك', 'Hand-picked products, competitive prices, and fast delivery to your door'],
    ['أكثر من 12,000 عميل سعيد', 'Over 12,000 happy customers'],
    ['اضغط الحالة لتحديثها', 'click a status to advance it'],
    ['سنتواصل معك للتوصيل', 'We will contact you for delivery'],
    ['تم تأكيد طلبك', 'Your order is confirmed'],
    ['تم استلام طلبك رقم', 'Order received: #'],
    ['أكمل اسم المنتج وسعره', 'Enter the product name and price'],
    ['لا منتجات بعد — أضف أولها', 'No products yet — add the first one'],
    ['لا منتجات مطابقة', 'No matching products'],
    ['لا منتجات', 'No products'],
    ['منتج جديد', 'New product'],
    ['أُضيف المنتج', 'Product added'],
    ['اسم المنتج', 'Product name'],
    ['إضافة منتج', 'Add product'],
    ['تفاصيل المنتج', 'Product details'],
    ['تصفّح المنتجات', 'Browse products'],
    ['ابحث عن منتج أو متجر', 'Search products or stores'],
    ['ابحث عن منتج', 'Search products'],
    ['أضِف إلى السلّة', 'Add to cart'],
    ['أُضيف إلى السلّة', 'Added to cart'],
    ['أُضيف إلى سلّتك', 'Added to your cart'],
    ['أضف للسلة', 'Add to cart'],
    ['أُضيف للسلة', 'Added to cart'],
    ['سلّتك فارغة', 'Your cart is empty'],
    ['السلة فارغة', 'Cart is empty'],
    ['سلّتك', 'Your cart'],
    ['إتمام الشراء', 'Checkout'],
    ['إتمام الطلب', 'Checkout'],
    ['متابعة التسوّق', 'Continue shopping'],
    ['متابعة الشراء', 'Continue to checkout'],
    ['بيانات التوصيل', 'Delivery details'],
    ['تأكيد الطلب', 'Confirm order'],
    ['تقديم الطلب', 'Place order'],
    ['رقم الطلب (مثال', 'Order number (e.g'],
    ['رقم الطلب', 'Order number'],
    ['رقم الجوّال', 'Phone number'],
    ['رقم جوّالك', 'Your phone'],
    ['الاسم الكامل', 'Full name'],
    ['متوسط الطلب', 'Avg order'],
    ['مخزون منخفض', 'Low stock'],
    ['المخزون', 'Stock'],
    ['مخزون', 'Stock'],
    ['المتوفّر', 'In stock'],
    ['نفدت التذاكر', 'Sold out'],
    ['نفدت', 'Sold out'],
    ['نفد', 'Sold out'],
    ['آخر', 'Only'],
    ['قيد التجهيز', 'Preparing'],
    ['تم الشحن', 'Shipped'],
    ['كل الطلبات', 'All orders'],
    ['لا طلبات بعد', 'No orders yet'],
    ['لا طلبات', 'No orders'],
    ['طلباتي', 'My orders'],
    ['الطلبات', 'Orders'],
    ['الإيراد', 'Revenue'],
    ['الإجمالي', 'Total'],
    ['المنتجات', 'Products'],
    ['منتجاتي', 'My products'],
    ['الفئة', 'Category'],
    ['السعر: من الأقل', 'Price: low to high'],
    ['السعر: من الأعلى', 'Price: high to low'],
    ['الأعلى تقييماً', 'Top rated'],
    ['السعر', 'Price'],
    ['مميّز', 'Featured'],
    ['الدفع', 'Checkout'],
    ['السلة', 'Cart'],

    // ── متجر: بطل/ثقة/بيانات ───────────────────────────────────────
    ['تسوّق بذكاء', 'Shop smart'],
    ['كل ما تحتاجه', 'Everything you need'],
    ['بين يديك', 'at your fingertips'],
    ['تسوّق الآن', 'Shop now'],
    ['لماذا نحن؟', 'Why us?'],
    ['شحن سريع', 'Fast shipping'],
    ['خلال 48 ساعة', 'Within 48 hours'],
    ['إرجاع مجّاني', 'Free returns'],
    ['خلال 14 يوماً', 'Within 14 days'],
    ['دفع آمن', 'Secure payment'],
    ['حماية كاملة', 'Fully protected'],
    ['نجيبك دائماً', 'Always here for you'],
    ['متجرنا', 'Our store'],
    ['المزايا', 'Features'],
    ['الخصوصية', 'Privacy'],
    ['تواصل', 'Contact'],
    ['المتجر', 'Store'],
    ['سماعات لاسلكية', 'Wireless Headphones'],
    ['سماعات بلوتوث بعزل ضوضاء وبطارية 30 ساعة', 'Bluetooth headphones with noise cancelling and 30h battery'],
    ['ساعة ذكية', 'Smart Watch'],
    ['تتبّع اللياقة، إشعارات، وشاشة', 'Fitness tracking, notifications, and an'],
    ['حقيبة ظهر', 'Backpack'],
    ['حقيبة مقاومة للماء بجيب لابتوب', 'Water-resistant backpack with laptop sleeve'],
    ['حذاء رياضي', 'Running Shoes'],
    ['خفيف ومريح للجري اليومي', 'Light and comfy for daily runs'],
    ['ماكينة قهوة', 'Coffee Machine'],
    ['إسبريسو احترافي بضغط 20 بار', 'Pro espresso with 20-bar pressure'],
    ['مصباح مكتب', 'Desk Lamp'],
    ['قابلة للتعتيم بثلاث درجات', 'dimmable with three levels'],
    ['لوحة مفاتيح', 'Keyboard'],
    ['ميكانيكية بإضاءة', 'Mechanical with'],
    ['واتصال لاسلكي', 'lighting and wireless'],
    ['نظّارة شمسية', 'Sunglasses'],
    ['بإطار خفيف', 'with a light frame'],
    ['إضاءة', 'Lighting'],
    ['حماية', 'Protection'],
    ['مدير المتجر', 'Store Manager'],
    ['إلكترونيات', 'Electronics'],
    ['أزياء', 'Fashion'],
    ['منزل', 'Home'],

    // ── توصيل الطعام ───────────────────────────────────────────────
    ['اختر من مطاعمنا المميّزة، أضف لسلّتك، وتتبّع طلبك لحظةً بلحظة', 'Pick from our featured restaurants, fill your cart, and track your order live'],
    ['أكثر من 8,000 طلب هذا الشهر', 'Over 8,000 orders this month'],
    ['توصيل خلال 30 دقيقة', 'Delivery within 30 minutes'],
    ['ألذّ الأطباق', 'The tastiest dishes'],
    ['تصل إليك', 'delivered to you'],
    ['لوحة المطعم — الطلبات الواردة', 'Restaurant Panel — Incoming Orders'],
    ['لوحة التوصيل — طلبات جاهزة', 'Delivery Panel — Ready Orders'],
    ['لوحة المطعم', 'Restaurant Panel'],
    ['لوحة السائق', 'Driver Panel'],
    ['لا طلبات جاهزة للتوصيل', 'No orders ready for delivery'],
    ['لا يوجد طلب بهذا الرقم', 'No order with that number'],
    ['تم تقديم طلبك برقم', 'Order placed: #'],
    ['تابعه من «تتبّع', 'track it in “Track'],
    ['جاهز للتوصيل', 'Ready for delivery'],
    ['قيد التوصيل', 'Out for delivery'],
    ['قيد التحضير', 'Being prepared'],
    ['تم التسليم', 'Delivered'],
    ['بانتظار سائق', 'Waiting for driver'],
    ['توصيل الطعام', 'Food Delivery'],
    ['اختر مطعمك', 'Choose your restaurant'],
    ['رجوع للمطاعم', 'Back to restaurants'],
    ['مطاعمنا', 'Our restaurants'],
    ['تتبّع طلبك', 'Track your order'],
    ['اطلب الآن', 'Order now'],
    ['مطعم البيت الشامي', 'Levant House'],
    ['شاورما دجاج', 'Chicken Shawarma'],
    ['فتّة حمّص', 'Hummus Fatteh'],
    ['تبولة', 'Tabbouleh'],
    ['بيتزا روما', 'Pizza Roma'],
    ['بيتزا مارغريتا', 'Margherita Pizza'],
    ['باستا الفريدو', 'Alfredo Pasta'],
    ['برجر هاوس', 'Burger House'],
    ['برجر لحم مزدوج', 'Double Beef Burger'],
    ['بطاطس مقلية', 'French Fries'],
    ['جمال (مدير الموقع', 'Jamal (Site Admin'],
    ['مدير المطعم', 'Restaurant Manager'],
    ['رجل التوصيل', 'Delivery Driver'],
    ['المطاعم', 'Restaurants'],
    ['المطعم', 'Restaurant'],
    ['التوصيل', 'Delivery'],
    ['شامي', 'Levantine'],
    ['إيطالي', 'Italian'],
    ['أمريكي', 'American'],
    ['تتبّع', 'Track'],
    ['الطلب', 'Order'],
    ['زائر', 'Guest'],
    ['مطعم', 'Restaurant'],
    ['طاقم', 'staff'],

    // ── حجوزات ─────────────────────────────────────────────────────
    ['اختر خدمتك، ثم اليوم والوقت المناسب — تأكيد فوري بلا انتظار', 'Pick your service, then a day and time — instant confirmation'],
    ['لوحة الإدارة — كل الحجوزات', 'Admin Panel — All Bookings'],
    ['اختر يوماً أولاً', 'Pick a day first'],
    ['تم تأكيد موعدك', 'Your appointment is confirmed'],
    ['حجز المواعيد', 'Appointments'],
    ['احجز في دقيقة', 'Book in a minute'],
    ['حجز موعد', 'Book appointment'],
    ['حجز جديد', 'New booking'],
    ['اختر الخدمة', 'Choose a service'],
    ['اختر اليوم', 'Pick a day'],
    ['اختر الوقت', 'Pick a time'],
    ['أكّد الحجز', 'Confirm booking'],
    ['تأكيد الحجز', 'Confirm booking'],
    ['رقم الحجز', 'Booking #'],
    ['قصّ وتصفيف', 'Cut and Style'],
    ['حلاقة ذقن', 'Beard Trim'],
    ['استشارة طبية', 'Medical Consult'],
    ['جلسة تدليك', 'Massage Session'],
    ['لا حجوزات بعد — ابدأ من «استكشف', 'No bookings yet — start from “Explore'],
    ['لا حجوزات بعد', 'No bookings yet'],
    ['لا حجوزات', 'No bookings'],
    ['كل الحجوزات', 'All bookings'],
    ['الحجوزات', 'Bookings'],
    ['حجوزاتي', 'My bookings'],
    ['موعدك', 'Your slot'],
    ['الموعد', 'Slot'],
    ['المواعيد', 'Appointments'],
    ['مواعيد', 'Appointments'],
    ['الخدمات', 'Services'],
    ['الخدمة', 'Service'],
    ['التأكيد', 'Confirm'],
    ['محجوز', 'Taken'],
    ['مؤكّد', 'Confirmed'],
    ['الوقت', 'Time'],
    ['الساعة', 'at'],
    ['اليوم', 'Today'],
    ['تمّ', 'Done'],

    // ── عقارات ─────────────────────────────────────────────────────
    ['شقق وفلل وأراضٍ مختارة في أبرز المدن — بفلاتر دقيقة وتفاصيل كاملة', 'Hand-picked apartments, villas, and land in top cities — precise filters, full details'],
    ['أكثر من 1,500 صفقة ناجحة', 'Over 1,500 successful deals'],
    ['عقارك القادم بانتظارك', 'Your next property awaits'],
    ['بيت أحلامك', 'your dream home'],
    ['ابحث عن', 'Find'],
    ['تصفّح العقارات', 'Browse properties'],
    ['لا عقارات مطابقة للتصفية', 'No properties match the filters'],
    ['لا عقارات', 'No properties'],
    ['عقار جديد', 'New property'],
    ['إضافة عقار', 'Add property'],
    ['عنوان العقار', 'Property title'],
    ['عدد الغرف (على الأقل', 'Rooms (at least'],
    ['أقصى سعر', 'Max price'],
    ['إعادة تعيين', 'Reset'],
    ['تصفية', 'Filter'],
    ['الفرز', 'Sort'],
    ['النوع', 'Type'],
    ['الأحدث', 'Newest'],
    ['الأرخص', 'Cheapest'],
    ['الأغلى', 'Priciest'],
    ['المساحة م', 'Area sqm'],
    ['الغرف', 'Rooms'],
    ['تواصل مع المعلن', 'Contact the advertiser'],
    ['أُرسل طلبك — سيتواصل معك المعلن', 'Request sent — the advertiser will contact you'],
    ['وصل طلبك للمعلن', 'Your request reached the advertiser'],
    ['إرسال طلب تواصل', 'Send contact request'],
    ['طلبات التواصل', 'Contact requests'],
    ['لا طلبات تواصل بعد', 'No contact requests yet'],
    ['طلبات جديدة', 'New requests'],
    ['قيمة المعروض', 'Listed value'],
    ['شقة عصرية بإطلالة', 'Modern Apartment with View'],
    ['شقة حديثة بتشطيب فاخر قرب الخدمات', 'Modern apartment, premium finish, near amenities'],
    ['فيلا فاخرة بمسبح', 'Luxury Villa with Pool'],
    ['فيلا مستقلة بحديقة ومسبح خاص', 'Detached villa with garden and private pool'],
    ['أرض سكنية', 'Residential Land'],
    ['أرض بمخطط معتمد وواجهتين', 'Approved plot with two frontages'],
    ['شقة اقتصادية', 'Budget Apartment'],
    ['مناسبة للعائلات الصغيرة قرب المترو', 'Great for small families, near the metro'],
    ['دوبلكس عائلي', 'Family Duplex'],
    ['دوبلكس بمدخلين ومجلس منفصل', 'Duplex with two entrances and separate majlis'],
    ['شقة بحرية', 'Seafront Apartment'],
    ['إطلالة بحرية مباشرة بتشطيب راقٍ', 'Direct sea view with refined finish'],
    ['إطلالة بحرية', 'Sea view'],
    ['مسبح مشترك', 'Shared pool'],
    ['تكييف مركزي', 'Central AC'],
    ['غرفة سائق', 'Driver room'],
    ['واجهتان', 'Two frontages'],
    ['مخطط معتمد', 'Approved plan'],
    ['قرب المترو', 'Near metro'],
    ['مدخلان', 'Two entrances'],
    ['مجلس', 'Majlis'],
    ['مصعد', 'Elevator'],
    ['موقف', 'Parking'],
    ['حديقة', 'Garden'],
    ['مسبح', 'Pool'],
    ['مدير المكتب', 'Office Manager'],
    ['العقارات', 'Properties'],
    ['عقارات', 'Real Estate'],
    ['جوّالك', 'Your phone'],
    ['عقار', 'property'],
    ['فيلا', 'Villa'],
    ['شقة', 'Apartment'],
    ['أرض', 'Land'],
    ['غرف', 'rooms'],

    // ── سوق متعدد البائعين ─────────────────────────────────────────
    ['تسوّق من عشرات البائعين المعتمدين، وأضف من متاجر مختلفة لسلّة واحدة', 'Shop dozens of approved sellers and mix stores in one cart'],
    ['سوق واحد · متاجر لا تُحصى', 'One market · countless stores'],
    ['في مكان واحد', 'in one place'],
    ['ابدأ التسوّق', 'Start shopping'],
    ['كل المتاجر', 'All stores'],
    ['لوحة متجري', 'My Store Panel'],
    ['لوحة البائع', 'Seller Panel'],
    ['طلبات متجري', 'My store orders'],
    ['متجر الحلويات', 'Sweets Shop'],
    ['ركن القهوة', 'Coffee Corner'],
    ['يدويات', 'Handmade'],
    ['كيكة شوكولاتة', 'Chocolate Cake'],
    ['دونات', 'Donuts'],
    ['لاتيه', 'Latte'],
    ['كوكيز', 'Cookies'],
    ['مدير السوق', 'Market Admin'],
    ['مبيعاتي', 'My sales'],
    ['المتاجر', 'Stores'],
    ['اعتماد', 'Approve'],
    ['معتمد', 'Approved'],
    ['تعليق', 'Suspend'],
    ['بانتظار', 'Pending'],
    ['السوق', 'Market'],
    ['متجر', 'Store'],
    ['سوق', 'Market'],

    // ── تاكسي ──────────────────────────────────────────────────────
    ['اختر وجهتك ونوع سيّارتك، واعرف السعر التقديري فوراً قبل الطلب', 'Pick your destination and car type, and see the fare estimate before you order'],
    ['وجهتك على بُعد نقرة', 'Your destination is a tap away'],
    ['في ثوانٍ', 'in seconds'],
    ['اطلب رحلتك', 'Request your ride'],
    ['اطلب رحلة', 'Request ride'],
    ['نوع السيّارة', 'Car type'],
    ['المسافة التقديرية', 'Estimated distance'],
    ['السعر التقديري', 'Estimated fare'],
    ['لا رحلات بعد — اطلب أولى رحلاتك', 'No rides yet — request your first'],
    ['طُلبت رحلتك — بانتظار سائق', 'Ride requested — waiting for a driver'],
    ['اختر وجهة مختلفة', 'Pick a different destination'],
    ['لا طلبات متاحة الآن', 'No requests available now'],
    ['لا رحلات جارية', 'No active rides'],
    ['لا رحلات بعد', 'No rides yet'],
    ['قبول الرحلة', 'Accept ride'],
    ['إنهاء الرحلة', 'Complete ride'],
    ['قبلت الرحلة', 'Ride accepted'],
    ['أُنهيت الرحلة', 'Ride completed'],
    ['رحلاتي الحالية', 'My active rides'],
    ['طلبات متاحة', 'Available requests'],
    ['مدير التشغيل', 'Operations Manager'],
    ['سائق: خالد', 'Driver: Khalid'],
    ['وسط المدينة', 'Downtown'],
    ['الحي الشمالي', 'North District'],
    ['المنطقة الصناعية', 'Industrial Area'],
    ['الكورنيش', 'Corniche'],
    ['المطار', 'Airport'],
    ['الجامعة', 'University'],
    ['في الطريق', 'On the way'],
    ['كل الرحلات', 'All rides'],
    ['رحلاتي', 'My rides'],
    ['أرباحي', 'My earnings'],
    ['اقتصادي إكسبريس', 'Economy Express'],
    ['اقتصادي', 'Economy'],
    ['عائلي', 'Family'],
    ['مريح', 'Comfort'],
    ['متاحة', 'Available'],
    ['جارية', 'Active'],
    ['السائق', 'Driver'],
    ['الراكب', 'Rider'],
    ['تاكسي', 'Taxi'],
    ['كم/س', 'km/h'],
    ['كم', 'km'],

    // ── سفر ────────────────────────────────────────────────────────
    ['احجز طيرانك وفندقك وسيّارتك في مكان واحد', 'Book your flight, hotel, and car in one place'],
    ['طيران · فنادق · سيّارات', 'Flights · Hotels · Cars'],
    ['وجهتك القادمة', 'Your next destination'],
    ['تبدأ هنا', 'starts here'],
    ['أهمّ الوجهات', 'Top destinations'],
    ['عروض مختارة', 'Featured deals'],
    ['ابحث عن رحلة طيران', 'Search flights'],
    ['بحث الرحلات', 'Search flights'],
    ['ابحث عن فندق', 'Search hotels'],
    ['بحث الفنادق', 'Search hotels'],
    ['استأجر سيّارة', 'Rent a car'],
    ['بحث السيّارات', 'Search cars'],
    ['المسافرون', 'Travelers'],
    ['المغادرة', 'Departure'],
    ['الوصول', 'Arrival'],
    ['الضيوف', 'Guests'],
    ['الاستلام', 'Pick-up'],
    ['الإرجاع', 'Drop-off'],
    ['هوية العلامة', 'Brand identity'],
    ['غيّر الاسم واللون فتُعاد العلامة كاملة حيّاً وتُحفظ', 'Change the name and colors — the brand updates live and is saved'],
    ['اسم العلامة', 'Brand name'],
    ['اللون الأساسي', 'Primary color'],
    ['حفظ وتطبيق', 'Save and apply'],
    ['حُفظت هوية العلامة', 'Brand identity saved'],
    ['حالة الربط', 'Connection status'],
    ['اسم المسافر', 'Traveler name'],
    ['أكمل اسم المسافر', 'Enter the traveler name'],
    ['للتواصل والتأكيد', 'for contact and confirmation'],
    ['تأكيد والدفع لاحقاً', 'Confirm — pay later'],
    ['تأكّد حجزك رقم', 'Booking confirmed: #'],
    ['أُلغي الحجز', 'Booking cancelled'],
    ['ناطحات سحاب وتسوّق', 'Skyscrapers and shopping'],
    ['حيث تلتقي القارّات', 'Where continents meet'],
    ['كورنيش وبحر أحمر', 'Corniche and Red Sea'],
    ['أهرامات وتاريخ', 'Pyramids and history'],
    ['العاصمة النابضة', 'The vibrant capital'],
    ['شرقية على الخليج', 'Eastern gem on the Gulf'],
    ['خصم الصيف على الفنادق', 'Summer hotel discount'],
    ['طيران + فندق', 'Flight + hotel'],
    ['إيجار سيّارة 3 أيّام', '3-day car rental'],
    ['عرض نهاية الأسبوع', 'Weekend deal'],
    ['الطيران الوطني', 'National Air'],
    ['خطوط الخليج', 'Gulf Lines'],
    ['الأناضول', 'Anatolia Air'],
    ['النيل للطيران', 'Nile Air'],
    ['منتجع الشاطئ', 'Beach Resort'],
    ['فندق الكورنيش', 'Corniche Hotel'],
    ['برج الأعمال', 'Business Tower'],
    ['نزل العليا', 'Olaya Inn'],
    ['مارينا سويتس', 'Marina Suites'],
    ['بيت البسفور', 'Bosphorus House'],
    ['إطلالة بحر', 'Sea view'],
    ['إطلالة مضيق', 'Strait view'],
    ['تويوتا يارِس', 'Toyota Yaris'],
    ['هيونداي سوناتا', 'Hyundai Sonata'],
    ['كيا كارنيفال', 'Kia Carnival'],
    ['نيسان صني', 'Nissan Sunny'],
    ['تويوتا كامري', 'Toyota Camry'],
    ['مرسيدس', 'Mercedes'],
    ['أوتوماتيك', 'Automatic'],
    ['يدوي', 'Manual'],
    ['فاخر', 'Luxury'],
    ['مقاعد', 'seats'],
    ['فطور', 'Breakfast'],
    ['قاعات', 'Halls'],
    ['جيم', 'Gym'],
    ['سبا', 'Spa'],
    ['مارينا', 'Marina'],
    ['واي‑فاي', 'Wi-Fi'],
    ['لا رحلات مباشرة على هذا المسار — نعرض كل الرحلات مرتّبة بالسعر', 'No direct flights on this route — showing all flights sorted by price'],
    ['لا عروض فعّالة حالياً', 'No active deals right now'],
    ['انسخ الكود', 'Copy code'],
    ['نُسخ الكود', 'Code copied'],
    ['الكود', 'Code'],
    ['كود خصم (اختياري', 'Promo code (optional'],
    ['تبدأ من', 'From'],
    ['خصم', 'off'],
    ['مسافر', 'traveler'],
    ['ليلة', 'night'],
    ['رحلة', 'Flight'],
    ['طيران', 'Flights'],
    ['فنادق', 'Hotels'],
    ['سيّارات', 'Cars'],
    ['العروض', 'Deals'],
    ['استكشف', 'Explore'],
    ['استكشاف', 'Explore'],
    ['يعمل حالياً ببيانات مبدئية', 'Currently running on seed data'],
    ['لتفعيل الجلب الحيّ اضبط', 'To enable live data set'],
    ['يرتدّ للبيانات المبدئية عند فشل الشبكة', 'falls back to seed data on network failure'],
    ['مربوط بـ', 'Connected to'],
    ['حيّ', 'live'],
    ['فعّال', 'Active'],
    ['الفعّالة', 'active'],
    ['تفعيل', 'Enable'],
    ['عملة', 'Currency'],

    // ── فعاليات وتذاكر ─────────────────────────────────────────────
    ['حفلات · رياضة · مؤتمرات · مسرح · ورش — تذاكرك بلمسة واحدة', 'Concerts · Sports · Conferences · Theater · Workshops — your tickets in one tap'],
    ['كل المناسبات في مكان واحد', 'All events in one place'],
    ['عِش اللحظة', 'Live the moment'],
    ['احجز تذكرتك', 'book your ticket'],
    ['ابحث عن حدث أو مكان', 'Search events or venues'],
    ['الأقرب تاريخاً', 'Soonest first'],
    ['لا مناسبات مطابقة للبحث', 'No events match your search'],
    ['لا مناسبات مطابقة', 'No matching events'],
    ['لا مناسبات بعد — أنشئ أولها', 'No events yet — create the first'],
    ['رجوع للمناسبات', 'Back to events'],
    ['إنشاء مناسبة', 'Create event'],
    ['اسم المناسبة', 'Event name'],
    ['القاعة/الملعب', 'Venue/stadium'],
    ['سعر التذكرة العادية', 'Standard ticket price'],
    ['عدد التذاكر', 'Ticket count'],
    ['نشر المناسبة', 'Publish event'],
    ['نُشرت المناسبة — ظهرت في الاستكشاف', 'Event published — now visible in Explore'],
    ['أكمل العنوان والسعر وعدد التذاكر', 'Enter the title, price, and ticket count'],
    ['كل المناسبات', 'All events'],
    ['المناسبات', 'Events'],
    ['مناسباتي', 'My events'],
    ['مناسبة من تنظيم', 'An event by'],
    ['مناسبة · بيع', 'event · sale'],
    ['بحث بالعنوان/المنظّم', 'Search by title/organizer'],
    ['أحدث المبيعات', 'Latest sales'],
    ['لا مبيعات بعد', 'No sales yet'],
    ['اسم المشترٍ', 'Buyer name'],
    ['أكمل اسم المشترٍ', 'Enter the buyer name'],
    ['لإرسال التذاكر', 'to send the tickets'],
    ['تأكيد وإصدار التذاكر', 'Confirm and issue tickets'],
    ['تمّ إصدار تذاكرك', 'Your tickets are issued'],
    ['لا تذاكر بعد — تصفّح «المناسبات» واحجز', 'No tickets yet — browse Events and book'],
    ['أُلغيت التذكرة واسترجعت المقاعد', 'Ticket cancelled and seats released'],
    ['إعادة المقاعد', 'Release seats'],
    ['اختر تذكرة واحدة على الأقل', 'Pick at least one ticket'],
    ['لم تختر تذاكر بعد', 'No tickets selected yet'],
    ['اختر تذاكرك', 'Pick your tickets'],
    ['لم يتبقَّ سوى', 'Only left:'],
    ['متبقّي', 'left:'],
    ['التذاكر المُباعة', 'Tickets sold'],
    ['تذاكري', 'My tickets'],
    ['تذاكر', 'Tickets'],
    ['تذكرة', 'ticket'],
    ['صالحة', 'Valid'],
    ['ليلة الطرب العربي', 'Arabic Music Night'],
    ['المسرح الكبير', 'Grand Theater'],
    ['أمسية غنائية استثنائية مع نخبة الفنانين وأوركسترا حيّة', 'An exceptional night with top artists and a live orchestra'],
    ['نهائي كأس المدينة', 'City Cup Final'],
    ['الملعب الأولمبي', 'Olympic Stadium'],
    ['المباراة النهائية المرتقبة — أجواء حماسية ومدرّجات كاملة', 'The long-awaited final — electric atmosphere, packed stands'],
    ['مؤتمر التقنية', 'Tech Conference'],
    ['مركز المؤتمرات', 'Convention Center'],
    ['ثلاثة أيّام من الجلسات وورش العمل مع روّاد التقنية', 'Three days of talks and workshops with tech leaders'],
    ['مسرحية «الرحلة', 'The Journey (Play'],
    ['مسرح الواجهة', 'Waterfront Theater'],
    ['عمل مسرحي كوميدي درامي يناسب العائلة', 'A comedy-drama stage play for the whole family'],
    ['ورشة التصوير الاحترافي', 'Pro Photography Workshop'],
    ['استوديو الضوء', 'Light Studio'],
    ['ورشة عملية ليوم كامل مع مدرّب معتمد — أدوات وشهادة', 'A full-day hands-on workshop with a certified trainer — gear and certificate'],
    ['حفلات موسيقية', 'Concerts'],
    ['ورش عمل', 'Workshops'],
    ['مؤتمرات', 'Conferences'],
    ['رياضة', 'Sports'],
    ['مسرح', 'Theater'],
    ['مدرّج عام', 'General stand'],
    ['الفئة الأولى', 'First class'],
    ['المقصورة', 'Box'],
    ['بلاتيني', 'Platinum'],
    ['أمامي', 'Front row'],
    ['حضور', 'Attendee'],
    ['محترف', 'Pro'],
    ['مقعد', 'Seat'],
    ['فئات', 'tiers'],
    ['شركة الفعّاليات', 'Events Co'],
    ['لوحة المنظّم', 'Organizer Panel'],
    ['المنظّمون', 'Organizers'],
    ['صفحة الحدث', 'Event page'],
    ['يُحدّد لاحقاً', 'TBA'],
    ['الملغاة', 'cancelled'],
    ['ملغاة', 'Cancelled'],
    ['ملغى', 'Cancelled'],
    ['كل المدن', 'All cities'],

    // ── تعليم (LMS) ────────────────────────────────────────────────
    ['دورات عملية بشهادات إتمام، ومتابعة لتقدّمك درساً بدرس', 'Practical courses with certificates, tracking your progress lesson by lesson'],
    ['تعلّم بوتيرتك', 'Learn at your pace'],
    ['مهارة جديدة', 'A new skill'],
    ['تبدأ اليوم', 'starts today'],
    ['ابحث عن دورة أو مدرّب', 'Search courses or instructors'],
    ['لا دورات مطابقة', 'No matching courses'],
    ['لا دورات بعد — أضف أولها', 'No courses yet — add the first'],
    ['اشترك مجاناً وابدأ التعلّم', 'Enroll free and start learning'],
    ['أنت مشترك بالفعل', 'You are already enrolled'],
    ['اشتركت في', 'Enrolled in'],
    ['أتممت الدورة! أحسنت', 'Course completed! Well done'],
    ['لم تشترك بعد — تصفّح «الدورات» وابدأ', 'Not enrolled yet — browse Courses and start'],
    ['اكتب عنوان الدورة', 'Enter the course title'],
    ['أُضيفت الدورة', 'Course added'],
    ['إضافة دورة', 'Add course'],
    ['عنوان الدورة', 'Course title'],
    ['إضافة درس', 'Add lesson'],
    ['عنوان الدرس', 'Lesson title'],
    ['المدة (دقائق', 'Duration (minutes'],
    ['أكمل العنوان والمدة', 'Enter the title and duration'],
    ['حفظ الدرس', 'Save lesson'],
    ['أُضيف الدرس', 'Lesson added'],
    ['لوحة المدرّب', 'Instructor Panel'],
    ['مدير الأكاديمية', 'Academy Admin'],
    ['أساسيات جافاسكربت', 'JavaScript Basics'],
    ['المتغيّرات', 'Variables'],
    ['الدوال', 'Functions'],
    ['مقدمة', 'Introduction'],
    ['تصميم واجهات', 'UI Design'],
    ['مبادئ التصميم', 'Design principles'],
    ['الألوان', 'Colors'],
    ['التسويق الرقمي', 'Digital Marketing'],
    ['وسائل التواصل', 'Social media'],
    ['أساسيات', 'Basics'],
    ['الإنجليزية للأعمال', 'Business English'],
    ['المراسلات', 'Correspondence'],
    ['الاجتماعات', 'Meetings'],
    ['أ. سارة', 'Ms. Sara'],
    ['أ. خالد', 'Mr. Khalid'],
    ['أ. منى', 'Ms. Mona'],
    ['أ. أحمد', 'Mr. Ahmed'],
    ['المشتركون', 'Enrolled'],
    ['مشترك', 'enrolled'],
    ['المدرّبون', 'Instructors'],
    ['المحتوى', 'Content'],
    ['الدورات', 'Courses'],
    ['دوراتي', 'My courses'],
    ['تعلّمي', 'My learning'],
    ['أكاديمية', 'Academy'],
    ['برمجة', 'Programming'],
    ['تصميم', 'Design'],
    ['تسويق', 'Marketing'],
    ['أعمال', 'Business'],
    ['لغات', 'Languages'],
    ['مبتدئ', 'Beginner'],
    ['متوسّط', 'Intermediate'],
    ['إتمام', 'Complete'],
    ['الدروس', 'Lessons'],
    ['دروس', 'lessons'],
    ['درس', 'lesson'],
    ['منشور', 'Published'],
    ['إخفاء', 'Hide'],
    ['نشر', 'Publish'],

    // ── مدرسة ──────────────────────────────────────────────────────
    ['جدولك ودرجاتك وواجباتك وإعلانات مدرستك — في مكان واحد', 'Your schedule, grades, homework, and school announcements — in one place'],
    ['بوّابتك الدراسية', 'Your school portal'],
    ['لوحة المعلّم', 'Teacher Panel'],
    ['إدارة المدرسة', 'School Administration'],
    ['الجدول الأسبوعي', 'Weekly schedule'],
    ['حصص اليوم', 'Today’s classes'],
    ['لا درجات مرصودة بعد', 'No grades recorded yet'],
    ['المعدّل العام', 'Overall average'],
    ['المعدّل', 'Average'],
    ['متوسّط الدرجات', 'Grade average'],
    ['لا واجبات حالياً', 'No homework right now'],
    ['أدخل درجة صحيحة', 'Enter a valid grade'],
    ['رُصدت درجة', 'Grade recorded for'],
    ['رصد درجة', 'Record grade'],
    ['الدرجة', 'Grade'],
    ['رصد', 'Record'],
    ['إضافة واجب', 'Add homework'],
    ['عنوان الواجب', 'Homework title'],
    ['اكتب عنوان الواجب', 'Enter the homework title'],
    ['أُضيف الواجب', 'Homework added'],
    ['نشر إعلان', 'Post announcement'],
    ['نص الإعلان', 'Announcement text'],
    ['اكتب نص الإعلان', 'Enter the announcement text'],
    ['نُشر الإعلان', 'Announcement posted'],
    ['الإعلانات المنشورة', 'Posted announcements'],
    ['لا إعلانات', 'No announcements'],
    ['الإعلانات', 'Announcements'],
    ['تمارين الفصل الثالث', 'Chapter 3 exercises'],
    ['تقرير عن الخلية', 'Report on the cell'],
    ['اجتماع أولياء الأمور الخميس القادم', 'Parent meeting next Thursday'],
    ['بداية الاختبارات الأسبوع المقبل', 'Exams start next week'],
    ['الرياضيات', 'Math'],
    ['العلوم', 'Science'],
    ['اللغة العربية', 'Arabic'],
    ['الإنجليزية', 'English'],
    ['الحاسب', 'Computer'],
    ['الرئيسية', 'Home'],
    ['الجدول', 'Schedule'],
    ['الدرجات', 'Grades'],
    ['درجاتي', 'My grades'],
    ['الواجبات', 'Homework'],
    ['الطلاب', 'Students'],
    ['المعلّم', 'Teacher'],
    ['المواد', 'Subjects'],
    ['الحصّة', 'Period'],
    ['مدرسة', 'School'],
    ['تسليم', 'due'],
    ['سالم', 'Salem'],
    ['نورة', 'Noura'],
    ['فهد', 'Fahd'],
    ['ليان', 'Layan'],

    // ── طقس/عملات (أدوات) ──────────────────────────────────────────
    ['اكتب اسم مدينة (مثل: الرياض، القاهرة، دبي', 'Type a city name (e.g. Riyadh, Cairo, Dubai'],
    ['اكتب اسم مدينة لعرض طقسها الحالي وتوقّعات الأسبوع', 'Type a city to see its current weather and weekly forecast'],
    ['اكتب اسم مدينة أولاً', 'Type a city name first'],
    ['جاري جلب الطقس لـ', 'Fetching weather for'],
    ['لم نعثر على', 'Could not find'],
    ['جرّب اسماً آخر', 'try another name'],
    ['تعذّر جلب الطقس الآن — حاول لاحقاً', 'Could not fetch weather — try again later'],
    ['مدن سريعة', 'Quick cities'],
    ['غائم جزئياً', 'Partly cloudy'],
    ['صافٍ غالباً', 'Mostly clear'],
    ['رذاذ خفيف', 'Light drizzle'],
    ['مطر خفيف', 'Light rain'],
    ['مطر غزير', 'Heavy rain'],
    ['عواصف رعدية', 'Thunderstorms'],
    ['غير معروف', 'Unknown'],
    ['زخّات', 'Showers'],
    ['صافٍ', 'Clear'],
    ['غائم', 'Cloudy'],
    ['ضباب', 'Fog'],
    ['ثلج', 'Snow'],
    ['مطر', 'Rain'],
    ['رياح', 'Wind'],
    ['الطقس', 'Weather'],
    ['طقس', 'Weather'],
    ['أسعار العملات الرقمية', 'Crypto Prices'],
    ['ابحث عن عملة', 'Search coins'],
    ['جاري تحديث الأسعار', 'Updating prices'],
    ['تعذّر جلب الأسعار الآن — اضغط «تحديث» للمحاولة', 'Could not fetch prices — press Refresh to retry'],
    ['لا نتائج للبحث', 'No search results'],
    ['لا بيانات بعد', 'No data yet'],
    ['القيمة السوقية', 'Market cap'],
    ['تحديث', 'Refresh'],
    ['محوّل العملات', 'Currency Converter'],
    ['اكتب مبلغاً واختر العملات ثم اضغط «تحويل', 'Enter an amount, pick currencies, then press Convert'],
    ['اكتب مبلغاً أكبر من صفر', 'Enter an amount above zero'],
    ['العملتان متطابقتان', 'Both currencies are the same'],
    ['جاري التحويل', 'Converting'],
    ['تعذّر جلب السعر الآن — حاول لاحقاً', 'Could not fetch the rate — try again later'],
    ['جاري جلب الأسعار', 'Fetching rates'],
    ['لا أسعار متاحة الآن', 'No rates available right now'],
    ['أسعار مقابل', 'Rates vs'],
    ['دولار أمريكي', 'US Dollar'],
    ['جنيه إسترليني', 'British Pound'],
    ['ريال سعودي', 'Saudi Riyal'],
    ['درهم إماراتي', 'UAE Dirham'],
    ['جنيه مصري', 'Egyptian Pound'],
    ['ين ياباني', 'Japanese Yen'],
    ['ليرة تركية', 'Turkish Lira'],
    ['دينار كويتي', 'Kuwaiti Dinar'],
    ['ريال قطري', 'Qatari Riyal'],
    ['يوان صيني', 'Chinese Yuan'],
    ['فرنك سويسري', 'Swiss Franc'],
    ['يورو', 'Euro'],
    ['تبديل', 'Swap'],
    ['تحويل', 'Convert'],
    ['عملات', 'Currencies'],
    ['بحث', 'Search'],

    // ── مدن وأيام وعموميات ─────────────────────────────────────────
    ['الرياض', 'Riyadh'],
    ['جدة', 'Jeddah'],
    ['الدمام', 'Dammam'],
    ['دبي', 'Dubai'],
    ['القاهرة', 'Cairo'],
    ['إسطنبول', 'Istanbul'],
    ['أبها', 'Abha'],
    ['الأحد', 'Sun'],
    ['الإثنين', 'Mon'],
    ['الثلاثاء', 'Tue'],
    ['الأربعاء', 'Wed'],
    ['الخميس', 'Thu'],
    ['الجمعة', 'Fri'],
    ['السبت', 'Sat'],
    ['لوحة الإدارة', 'Admin Panel'],
    ['لوحة المدير', 'Admin Panel'],
    ['الإدارة', 'Admin'],
    ['اللوحة', 'Panel'],
    ['المدير', 'Admin'],
    ['مدير المنصّة', 'Platform Admin'],
    ['مكتملة', 'Completed'],
    ['مكتمل', 'Completed'],
    ['إلغاء', 'Cancel'],
    ['حذف', 'Delete'],
    ['إضافة', 'Add'],
    ['إيقاف', 'Stop'],
    ['موقوف', 'Stopped'],
    ['الكل', 'All'],
    ['جديد', 'New'],
    ['عادي', 'Standard'],
    ['يوم', 'day'],
    ['أضف', 'Add'],
    ['اسمك', 'Your name'],
    ['المدينة', 'City'],
    ['المكان', 'Venue'],
    ['العنوان', 'Address'],
    ['التاريخ', 'Date'],
    ['الرمز', 'Icon'],
    ['رمز', 'Icon'],
    ['مثال', 'e.g'],
    ['البريد / الجوّال', 'Email / phone'],
    ['دعم', 'Support'],
    ['العميل', 'Customer'],
    ['الطالب', 'Student'],
    ['طلب', 'Order'],
    ['منتج', 'item'],
    ['من', 'From'],
    ['إلى', 'To'],
    ['في', 'in'],
    [' ﷼', ' SAR'],
    ['﷼', 'SAR'],
];

// بالأطول أولاً — يمنع أن تأكل الترجمة القصيرة جزءاً من سلسلة أطول
const ORDERED = [...DICT].sort((a, b) => b[0].length - a[0].length);

/** يترجم نصاً واحداً (HTML أو JS) بالقاموس الحتمي. */
export function localizeText(text = '') {
    let out = text;
    for (const [ar, en] of ORDERED) out = out.split(ar).join(en);
    return out;
}

/** نسبة العربية المتبقية بعد التوطين (لقياس التغطية في الاختبارات). */
export function arabicRatio(text = '') {
    const ar = (text.match(/[؀-ۿ]/g) || []).length;
    return text.length ? ar / text.length : 0;
}

/**
 * 🧩 المدخل الرئيسي: يوطّن ملفات قالب كاملة حسب اللغة.
 * - lang !== 'en' → تُعاد الملفات كما هي (العربية هي الأصل).
 * - index.html: قلب lang/dir + ترجمة القاموس.
 * - *.js: ترجمة القاموس (سلاسل عربية فقط — الكود لا يُمسّ).
 * - *.css: يُلحق تصحيح توسيط الـ toast للاتجاه الجديد.
 */
export function localizeTemplateFiles(files = [], lang = 'ar') {
    if (lang !== 'en') return files;
    return files.map(f => {
        if (f.name.endsWith('.html')) {
            let html = localizeText(f.content)
                .replace(/lang="ar"/g, 'lang="en"')
                .replace(/dir="rtl"/g, 'dir="ltr"');
            return { ...f, content: html };
        }
        if (f.name.endsWith('.js')) {
            return { ...f, content: localizeText(f.content) };
        }
        if (f.name.endsWith('.css')) {
            // toast كان يفترض RTL (translateX(50%)) — في LTR يلزم -50%
            return { ...f, content: f.content + '\nhtml[dir=ltr] .toast{transform:translateX(-50%)}\n' };
        }
        return f;
    });
}
