/**
 * 🌐 Template Localizer — تسليم القوالب بلغة المستخدم المختارة.
 *
 * المشكلة: القوالب مكتوبة بالعربية (lang/dir/نصوص) فتصل عربيةً لمن اختار
 * الإنجليزية. الحل الحتمي (لا LLM يبتر الملفات): قاموس مطابقة حرفية للسلاسل
 * الظاهرة للمستخدم يُطبَّق بالأطول-أولاً على HTML/JS + قلب lang/dir +
 * تصحيح توسيط الـ toast للاتجاه الجديد. التعليقات البرمجية تبقى كما هي إن لم
 * تطابق، والدوال لا تُمسّ إطلاقاً (استبدال نصّي داخل سلاسل عربية فقط).
 *
 * قاعدة صارمة: لا فواصل عليا (') في أي ترجمة — كي لا تكسر سلاسل JS المفردة.
 */

// [عربي, إنجليزي] — التغطية الكاملة لسلاسل القوالب الظاهرة (مرتّبة منطقياً؛
// الترتيب الفعلي عند التطبيق: بالأطول أولاً لمنع المطابقات الجزئية).
const DICT = [
    // ── عام/دخول/حسابات ─────────────────────────────────────────────
    ['العميل يتسوّق بلا تسجيل — هذا الدخول للإدارة فقط', 'Customers shop without signing in — this login is for management only'],
    ['الزائر يتصفّح بلا تسجيل — هذا الدخول للإدارة فقط', 'Visitors browse without signing in — this login is for management only'],
    ['ادخل بحسابك لتُوجَّه لصفحتك حسب دورك', 'Sign in and you will be routed to your page by role'],
    ['ادخل بحسابك لتُوجَّه لصفحتك', 'Sign in to be routed to your page'],
    ['سجّل لإتمام طلبك — دقائق فقط', 'Register to complete your order — it takes a minute'],
    ['سجّل لطلب رحلتك — دقائق فقط', 'Register to request your ride — it takes a minute'],
    ['سجّل لتبدأ التعلّم وحفظ تقدّمك', 'Register to start learning and save your progress'],
    ['سجّل لحفظ تذاكرك ومتابعتها', 'Register to save and track your tickets'],
    ['سجّل لحفظ حجوزاتك', 'Register to save your bookings'],
    ['سجّل لإكمال طلبك', 'Register to complete your order'],
    ['أدخل اسمك من فضلك', 'Please enter your name'],
    ['تم تسجيل الخروج', 'Signed out'],
    ['تسجيل الدخول', 'Sign in'],
    ['اسم المستخدم', 'Username'],
    ['كلمة المرور', 'Password'],
    ['بيانات غير صحيحة', 'Invalid credentials'],
    ['حسابات تجربة', 'Demo accounts'],
    ['حساب إدارة تجربة', 'Demo admin account'],
    ['إنشاء حساب عميل', 'Create customer account'],
    ['إنشاء حساب راكب', 'Create rider account'],
    ['إنشاء حساب مسافر', 'Create traveler account'],
    ['إنشاء حساب طالب', 'Create student account'],
    ['إنشاء حساب', 'Create account'],
    ['لديك حساب طاقم؟', 'Have a staff account?'],
    ['لديك حساب إدارة؟', 'Have an admin account?'],
    ['عميل جديد؟', 'New customer?'],
    ['راكب جديد؟', 'New rider?'],
    ['مسافر جديد؟', 'New traveler?'],
    ['طالب جديد؟', 'New student?'],
    ['مستخدم جديد؟', 'New user?'],
    ['تسجيل ومتابعة', 'Register and continue'],
    ['تسجيل وطلب الرحلة', 'Register and request ride'],
    ['تسجيل وبدء التعلّم', 'Register and start learning'],
    ['دخول الموظّف', 'Staff sign in'],
    ['دخول الطاقم', 'Staff sign in'],
    ['دخول المدير', 'Admin sign in'],
    ['تسجيل', 'Register'],
    ['تجريبي', 'Demo'],
    ['تجربة', 'Demo'],
    ['دخول', 'Sign in'],
    ['خروج', 'Sign out'],
    ['مرحباً', 'Welcome'],
    ['أهلاً', 'Hello'],

    // ── تجارة/سلة/طلبات ────────────────────────────────────────────
    ['منتجات مختارة بعناية، أسعار منافسة، وتوصيل سريع لبابك', 'Hand-picked products, competitive prices, and fast delivery to your door'],
    ['أكثر من 12,000 عميل سعيد', 'Over 12,000 happy customers'],
    ['اضغط الحالة لتحديثها', 'click a status to advance it'],
    ['سنتواصل معك للتوصيل', 'We will contact you for delivery'],
    ['تم تأكيد طلبك', 'Your order is confirmed'],
    ['تم استلام طلبك رقم', 'Order received: #'],
    ['أكمل اسم المنتج وسعره', 'Enter the product name and price'],
    ['لا منتجات بعد — أضف أولها', 'No products yet — add the first one'],
    ['لا منتجات مطابقة', 'No matching products'],
    ['لا منتجات', 'No products'],
    ['منتج جديد', 'New product'],
    ['أُضيف المنتج', 'Product added'],
    ['اسم المنتج', 'Product name'],
    ['إضافة منتج', 'Add product'],
    ['تفاصيل المنتج', 'Product details'],
    ['تصفّح المنتجات', 'Browse products'],
    ['ابحث عن منتج أو متجر', 'Search products or stores'],
    ['ابحث عن منتج', 'Search products'],
    ['أضِف إلى السلّة', 'Add to cart'],
    ['أُضيف إلى السلّة', 'Added to cart'],
    ['أُضيف إلى سلّتك', 'Added to your cart'],
    ['أضف للسلة', 'Add to cart'],
    ['أُضيف للسلة', 'Added to cart'],
    ['سلّتك فارغة', 'Your cart is empty'],
    ['السلة فارغة', 'Cart is empty'],
    ['سلّتك', 'Your cart'],
    ['إتمام الشراء', 'Checkout'],
    ['إتمام الطلب', 'Checkout'],
    ['متابعة التسوّق', 'Continue shopping'],
    ['متابعة الشراء', 'Continue to checkout'],
    ['بيانات التوصيل', 'Delivery details'],
    ['تأكيد الطلب', 'Confirm order'],
    ['تقديم الطلب', 'Place order'],
    ['رقم الطلب (مثال', 'Order number (e.g'],
    ['رقم الطلب', 'Order number'],
    ['رقم الجوّال', 'Phone number'],
    ['رقم جوّالك', 'Your phone'],
    ['الاسم الكامل', 'Full name'],
    ['متوسط الطلب', 'Avg order'],
    ['مخزون منخفض', 'Low stock'],
    ['المخزون', 'Stock'],
    ['مخزون', 'Stock'],
    ['المتوفّر', 'In stock'],
    ['نفدت التذاكر', 'Sold out'],
    ['نفدت', 'Sold out'],
    ['نفد', 'Sold out'],
    ['آخر', 'Only'],
    ['قيد التجهيز', 'Preparing'],
    ['تم الشحن', 'Shipped'],
    ['كل الطلبات', 'All orders'],
    ['لا طلبات بعد', 'No orders yet'],
    ['لا طلبات', 'No orders'],
    ['طلباتي', 'My orders'],
    ['الطلبات', 'Orders'],
    ['الإيراد', 'Revenue'],
    ['الإجمالي', 'Total'],
    ['المنتجات', 'Products'],
    ['منتجاتي', 'My products'],
    ['الفئة', 'Category'],
    ['السعر: من الأقل', 'Price: low to high'],
    ['السعر: من الأعلى', 'Price: high to low'],
    ['الأعلى تقييماً', 'Top rated'],
    ['السعر', 'Price'],
    ['مميّز', 'Featured'],
    ['الدفع', 'Checkout'],
    ['السلة', 'Cart'],

    // ── متجر: بطل/ثقة/بيانات ───────────────────────────────────────
    ['تسوّق بذكاء', 'Shop smart'],
    ['كل ما تحتاجه', 'Everything you need'],
    ['بين يديك', 'at your fingertips'],
    ['تسوّق الآن', 'Shop now'],
    ['لماذا نحن؟', 'Why us?'],
    ['شحن سريع', 'Fast shipping'],
    ['خلال 48 ساعة', 'Within 48 hours'],
    ['إرجاع مجّاني', 'Free returns'],
    ['خلال 14 يوماً', 'Within 14 days'],
    ['دفع آمن', 'Secure payment'],
    ['حماية كاملة', 'Fully protected'],
    ['نجيبك دائماً', 'Always here for you'],
    ['متجرنا', 'Our store'],
    ['المزايا', 'Features'],
    ['الخصوصية', 'Privacy'],
    ['تواصل', 'Contact'],
    ['المتجر', 'Store'],
    ['سماعات لاسلكية', 'Wireless Headphones'],
    ['سماعات بلوتوث بعزل ضوضاء وبطارية 30 ساعة', 'Bluetooth headphones with noise cancelling and 30h battery'],
    ['ساعة ذكية', 'Smart Watch'],
    ['تتبّع اللياقة، إشعارات، وشاشة', 'Fitness tracking, notifications, and an'],
    ['حقيبة ظهر', 'Backpack'],
    ['حقيبة مقاومة للماء بجيب لابتوب', 'Water-resistant backpack with laptop sleeve'],
    ['حذاء رياضي', 'Running Shoes'],
    ['خفيف ومريح للجري اليومي', 'Light and comfy for daily runs'],
    ['ماكينة قهوة', 'Coffee Machine'],
    ['إسبريسو احترافي بضغط 20 بار', 'Pro espresso with 20-bar pressure'],
    ['مصباح مكتب', 'Desk Lamp'],
    ['قابلة للتعتيم بثلاث درجات', 'dimmable with three levels'],
    ['لوحة مفاتيح', 'Keyboard'],
    ['ميكانيكية بإضاءة', 'Mechanical with'],
    ['واتصال لاسلكي', 'lighting and wireless'],
    ['نظّارة شمسية', 'Sunglasses'],
    ['بإطار خفيف', 'with a light frame'],
    ['إضاءة', 'Lighting'],
    ['حماية', 'Protection'],
    ['مدير المتجر', 'Store Manager'],
    ['إلكترونيات', 'Electronics'],
    ['أزياء', 'Fashion'],
    ['منزل', 'Home'],

    // ── توصيل الطعام ───────────────────────────────────────────────
    ['اختر من مطاعمنا المميّزة، أضف لسلّتك، وتتبّع طلبك لحظةً بلحظة', 'Pick from our featured restaurants, fill your cart, and track your order live'],
    ['أكثر من 8,000 طلب هذا الشهر', 'Over 8,000 orders this month'],
    ['توصيل خلال 30 دقيقة', 'Delivery within 30 minutes'],
    ['ألذّ الأطباق', 'The tastiest dishes'],
    ['تصل إليك', 'delivered to you'],
    ['لوحة المطعم — الطلبات الواردة', 'Restaurant Panel — Incoming Orders'],
    ['لوحة التوصيل — طلبات جاهزة', 'Delivery Panel — Ready Orders'],
    ['لوحة المطعم', 'Restaurant Panel'],
    ['لوحة السائق', 'Driver Panel'],
    ['لا طلبات جاهزة للتوصيل', 'No orders ready for delivery'],
    ['لا يوجد طلب بهذا الرقم', 'No order with that number'],
    ['تم تقديم طلبك برقم', 'Order placed: #'],
    ['تابعه من «تتبّع', 'track it in “Track'],
    ['جاهز للتوصيل', 'Ready for delivery'],
    ['قيد التوصيل', 'Out for delivery'],
    ['قيد التحضير', 'Being prepared'],
    ['تم التسليم', 'Delivered'],
    ['بانتظار سائق', 'Waiting for driver'],
    ['توصيل الطعام', 'Food Delivery'],
    ['اختر مطعمك', 'Choose your restaurant'],
    ['رجوع للمطاعم', 'Back to restaurants'],
    ['مطاعمنا', 'Our restaurants'],
    ['تتبّع طلبك', 'Track your order'],
    ['اطلب الآن', 'Order now'],
    ['مطعم البيت الشامي', 'Levant House'],
    ['شاورما دجاج', 'Chicken Shawarma'],
    ['فتّة حمّص', 'Hummus Fatteh'],
    ['تبولة', 'Tabbouleh'],
    ['بيتزا روما', 'Pizza Roma'],
    ['بيتزا مارغريتا', 'Margherita Pizza'],
    ['باستا الفريدو', 'Alfredo Pasta'],
    ['برجر هاوس', 'Burger House'],
    ['برجر لحم مزدوج', 'Double Beef Burger'],
    ['بطاطس مقلية', 'French Fries'],
    ['جمال (مدير الموقع', 'Jamal (Site Admin'],
    ['مدير المطعم', 'Restaurant Manager'],
    ['رجل التوصيل', 'Delivery Driver'],
    ['المطاعم', 'Restaurants'],
    ['المطعم', 'Restaurant'],
    ['التوصيل', 'Delivery'],
    ['شامي', 'Levantine'],
    ['إيطالي', 'Italian'],
    ['أمريكي', 'American'],
    ['تتبّع', 'Track'],
    ['الطلب', 'Order'],
    ['زائر', 'Guest'],
    ['مطعم', 'Restaurant'],
    ['طاقم', 'staff'],

    // ── حجوزات ─────────────────────────────────────────────────────
    ['اختر خدمتك، ثم اليوم والوقت المناسب — تأكيد فوري بلا انتظار', 'Pick your service, then a day and time — instant confirmation'],
    ['لوحة الإدارة — كل الحجوزات', 'Admin Panel — All Bookings'],
    ['اختر يوماً أولاً', 'Pick a day first'],
    ['تم تأكيد موعدك', 'Your appointment is confirmed'],
    ['حجز المواعيد', 'Appointments'],
    ['احجز في دقيقة', 'Book in a minute'],
    ['حجز موعد', 'Book appointment'],
    ['حجز جديد', 'New booking'],
    ['اختر الخدمة', 'Choose a service'],
    ['اختر اليوم', 'Pick a day'],
    ['اختر الوقت', 'Pick a time'],
    ['أكّد الحجز', 'Confirm booking'],
    ['تأكيد الحجز', 'Confirm booking'],
    ['رقم الحجز', 'Booking #'],
    ['قصّ وتصفيف', 'Cut and Style'],
    ['حلاقة ذقن', 'Beard Trim'],
    ['استشارة طبية', 'Medical Consult'],
    ['جلسة تدليك', 'Massage Session'],
    ['لا حجوزات بعد — ابدأ من «استكشف', 'No bookings yet — start from “Explore'],
    ['لا حجوزات بعد', 'No bookings yet'],
    ['لا حجوزات', 'No bookings'],
    ['كل الحجوزات', 'All bookings'],
    ['الحجوزات', 'Bookings'],
    ['حجوزاتي', 'My bookings'],
    ['موعدك', 'Your slot'],
    ['الموعد', 'Slot'],
    ['المواعيد', 'Appointments'],
    ['مواعيد', 'Appointments'],
    ['الخدمات', 'Services'],
    ['الخدمة', 'Service'],
    ['التأكيد', 'Confirm'],
    ['محجوز', 'Taken'],
    ['مؤكّد', 'Confirmed'],
    ['الوقت', 'Time'],
    ['الساعة', 'at'],
    ['اليوم', 'Today'],
    ['تمّ', 'Done'],

    // ── عقارات ─────────────────────────────────────────────────────
    ['شقق وفلل وأراضٍ مختارة في أبرز المدن — بفلاتر دقيقة وتفاصيل كاملة', 'Hand-picked apartments, villas, and land in top cities — precise filters, full details'],
    ['أكثر من 1,500 صفقة ناجحة', 'Over 1,500 successful deals'],
    ['عقارك القادم بانتظارك', 'Your next property awaits'],
    ['بيت أحلامك', 'your dream home'],
    ['ابحث عن', 'Find'],
    ['تصفّح العقارات', 'Browse properties'],
    ['لا عقارات مطابقة للتصفية', 'No properties match the filters'],
    ['لا عقارات', 'No properties'],
    ['عقار جديد', 'New property'],
    ['إضافة عقار', 'Add property'],
    ['عنوان العقار', 'Property title'],
    ['عدد الغرف (على الأقل', 'Rooms (at least'],
    ['أقصى سعر', 'Max price'],
    ['إعادة تعيين', 'Reset'],
    ['تصفية', 'Filter'],
    ['الفرز', 'Sort'],
    ['النوع', 'Type'],
    ['الأحدث', 'Newest'],
    ['الأرخص', 'Cheapest'],
    ['الأغلى', 'Priciest'],
    ['المساحة م', 'Area sqm'],
    ['الغرف', 'Rooms'],
    ['تواصل مع المعلن', 'Contact the advertiser'],
    ['أُرسل طلبك — سيتواصل معك المعلن', 'Request sent — the advertiser will contact you'],
    ['وصل طلبك للمعلن', 'Your request reached the advertiser'],
    ['إرسال طلب تواصل', 'Send contact request'],
    ['طلبات التواصل', 'Contact requests'],
    ['لا طلبات تواصل بعد', 'No contact requests yet'],
    ['طلبات جديدة', 'New requests'],
    ['قيمة المعروض', 'Listed value'],
    ['شقة عصرية بإطلالة', 'Modern Apartment with View'],
    ['شقة حديثة بتشطيب فاخر قرب الخدمات', 'Modern apartment, premium finish, near amenities'],
    ['فيلا فاخرة بمسبح', 'Luxury Villa with Pool'],
    ['فيلا مستقلة بحديقة ومسبح خاص', 'Detached villa with garden and private pool'],
    ['أرض سكنية', 'Residential Land'],
    ['أرض بمخطط معتمد وواجهتين', 'Approved plot with two frontages'],
    ['شقة اقتصادية', 'Budget Apartment'],
    ['مناسبة للعائلات الصغيرة قرب المترو', 'Great for small families, near the metro'],
    ['دوبلكس عائلي', 'Family Duplex'],
    ['دوبلكس بمدخلين ومجلس منفصل', 'Duplex with two entrances and separate majlis'],
    ['شقة بحرية', 'Seafront Apartment'],
    ['إطلالة بحرية مباشرة بتشطيب راقٍ', 'Direct sea view with refined finish'],
    ['إطلالة بحرية', 'Sea view'],
    ['مسبح مشترك', 'Shared pool'],
    ['تكييف مركزي', 'Central AC'],
    ['غرفة سائق', 'Driver room'],
    ['واجهتان', 'Two frontages'],
    ['مخطط معتمد', 'Approved plan'],
    ['قرب المترو', 'Near metro'],
    ['مدخلان', 'Two entrances'],
    ['مجلس', 'Majlis'],
    ['مصعد', 'Elevator'],
    ['موقف', 'Parking'],
    ['حديقة', 'Garden'],
    ['مسبح', 'Pool'],
    ['مدير المكتب', 'Office Manager'],
    ['العقارات', 'Properties'],
    ['عقارات', 'Real Estate'],
    ['جوّالك', 'Your phone'],
    ['عقار', 'property'],
    ['فيلا', 'Villa'],
    ['شقة', 'Apartment'],
    ['أرض', 'Land'],
    ['غرف', 'rooms'],

    // ── سوق متعدد البائعين ─────────────────────────────────────────
    ['تسوّق من عشرات البائعين المعتمدين، وأضف من متاجر مختلفة لسلّة واحدة', 'Shop dozens of approved sellers and mix stores in one cart'],
    ['سوق واحد · متاجر لا تُحصى', 'One market · countless stores'],
    ['في مكان واحد', 'in one place'],
    ['ابدأ التسوّق', 'Start shopping'],
    ['كل المتاجر', 'All stores'],
    ['لوحة متجري', 'My Store Panel'],
    ['لوحة البائع', 'Seller Panel'],
    ['طلبات متجري', 'My store orders'],
    ['متجر الحلويات', 'Sweets Shop'],
    ['ركن القهوة', 'Coffee Corner'],
    ['يدويات', 'Handmade'],
    ['كيكة شوكولاتة', 'Chocolate Cake'],
    ['دونات', 'Donuts'],
    ['لاتيه', 'Latte'],
    ['كوكيز', 'Cookies'],
    ['مدير السوق', 'Market Admin'],
    ['مبيعاتي', 'My sales'],
    ['المتاجر', 'Stores'],
    ['اعتماد', 'Approve'],
    ['معتمد', 'Approved'],
    ['تعليق', 'Suspend'],
    ['بانتظار', 'Pending'],
    ['السوق', 'Market'],
    ['متجر', 'Store'],
    ['سوق', 'Market'],

    // ── تاكسي ──────────────────────────────────────────────────────
    ['اختر وجهتك ونوع سيّارتك، واعرف السعر التقديري فوراً قبل الطلب', 'Pick your destination and car type, and see the fare estimate before you order'],
    ['وجهتك على بُعد نقرة', 'Your destination is a tap away'],
    ['في ثوانٍ', 'in seconds'],
    ['اطلب رحلتك', 'Request your ride'],
    ['اطلب رحلة', 'Request ride'],
    ['نوع السيّارة', 'Car type'],
    ['المسافة التقديرية', 'Estimated distance'],
    ['السعر التقديري', 'Estimated fare'],
    ['لا رحلات بعد — اطلب أولى رحلاتك', 'No rides yet — request your first'],
    ['طُلبت رحلتك — بانتظار سائق', 'Ride requested — waiting for a driver'],
    ['اختر وجهة مختلفة', 'Pick a different destination'],
    ['لا طلبات متاحة الآن', 'No requests available now'],
    ['لا رحلات جارية', 'No active rides'],
    ['لا رحلات بعد', 'No rides yet'],
    ['قبول الرحلة', 'Accept ride'],
    ['إنهاء الرحلة', 'Complete ride'],
    ['قبلت الرحلة', 'Ride accepted'],
    ['أُنهيت الرحلة', 'Ride completed'],
    ['رحلاتي الحالية', 'My active rides'],
    ['طلبات متاحة', 'Available requests'],
    ['مدير التشغيل', 'Operations Manager'],
    ['سائق: خالد', 'Driver: Khalid'],
    ['وسط المدينة', 'Downtown'],
    ['الحي الشمالي', 'North District'],
    ['المنطقة الصناعية', 'Industrial Area'],
    ['الكورنيش', 'Corniche'],
    ['المطار', 'Airport'],
    ['الجامعة', 'University'],
    ['في الطريق', 'On the way'],
    ['كل الرحلات', 'All rides'],
    ['رحلاتي', 'My rides'],
    ['أرباحي', 'My earnings'],
    ['اقتصادي إكسبريس', 'Economy Express'],
    ['اقتصادي', 'Economy'],
    ['عائلي', 'Family'],
    ['مريح', 'Comfort'],
    ['متاحة', 'Available'],
    ['جارية', 'Active'],
    ['السائق', 'Driver'],
    ['الراكب', 'Rider'],
    ['تاكسي', 'Taxi'],
    ['كم/س', 'km/h'],
    ['كم', 'km'],

    // ── سفر ────────────────────────────────────────────────────────
    ['احجز طيرانك وفندقك وسيّارتك في مكان واحد', 'Book your flight, hotel, and car in one place'],
    ['طيران · فنادق · سيّارات', 'Flights · Hotels · Cars'],
    ['وجهتك القادمة', 'Your next destination'],
    ['تبدأ هنا', 'starts here'],
    ['أهمّ الوجهات', 'Top destinations'],
    ['عروض مختارة', 'Featured deals'],
    ['ابحث عن رحلة طيران', 'Search flights'],
    ['بحث الرحلات', 'Search flights'],
    ['ابحث عن فندق', 'Search hotels'],
    ['بحث الفنادق', 'Search hotels'],
    ['استأجر سيّارة', 'Rent a car'],
    ['بحث السيّارات', 'Search cars'],
    ['المسافرون', 'Travelers'],
    ['المغادرة', 'Departure'],
    ['الوصول', 'Arrival'],
    ['الضيوف', 'Guests'],
    ['الاستلام', 'Pick-up'],
    ['الإرجاع', 'Drop-off'],
    ['هوية العلامة', 'Brand identity'],
    ['غيّر الاسم واللون فتُعاد العلامة كاملة حيّاً وتُحفظ', 'Change the name and colors — the brand updates live and is saved'],
    ['اسم العلامة', 'Brand name'],
    ['اللون الأساسي', 'Primary color'],
    ['حفظ وتطبيق', 'Save and apply'],
    ['حُفظت هوية العلامة', 'Brand identity saved'],
    ['حالة الربط', 'Connection status'],
    ['اسم المسافر', 'Traveler name'],
    ['أكمل اسم المسافر', 'Enter the traveler name'],
    ['للتواصل والتأكيد', 'for contact and confirmation'],
    ['تأكيد والدفع لاحقاً', 'Confirm — pay later'],
    ['تأكّد حجزك رقم', 'Booking confirmed: #'],
    ['أُلغي الحجز', 'Booking cancelled'],
    ['ناطحات سحاب وتسوّق', 'Skyscrapers and shopping'],
    ['حيث تلتقي القارّات', 'Where continents meet'],
    ['كورنيش وبحر أحمر', 'Corniche and Red Sea'],
    ['أهرامات وتاريخ', 'Pyramids and history'],
    ['العاصمة النابضة', 'The vibrant capital'],
    ['شرقية على الخليج', 'Eastern gem on the Gulf'],
    ['خصم الصيف على الفنادق', 'Summer hotel discount'],
    ['طيران + فندق', 'Flight + hotel'],
    ['إيجار سيّارة 3 أيّام', '3-day car rental'],
    ['عرض نهاية الأسبوع', 'Weekend deal'],
    ['الطيران الوطني', 'National Air'],
    ['خطوط الخليج', 'Gulf Lines'],
    ['الأناضول', 'Anatolia Air'],
    ['النيل للطيران', 'Nile Air'],
    ['منتجع الشاطئ', 'Beach Resort'],
    ['فندق الكورنيش', 'Corniche Hotel'],
    ['برج الأعمال', 'Business Tower'],
    ['نزل العليا', 'Olaya Inn'],
    ['مارينا سويتس', 'Marina Suites'],
    ['بيت البسفور', 'Bosphorus House'],
    ['إطلالة بحر', 'Sea view'],
    ['إطلالة مضيق', 'Strait view'],
    ['تويوتا يارِس', 'Toyota Yaris'],
    ['هيونداي سوناتا', 'Hyundai Sonata'],
    ['كيا كارنيفال', 'Kia Carnival'],
    ['نيسان صني', 'Nissan Sunny'],
    ['تويوتا كامري', 'Toyota Camry'],
    ['مرسيدس', 'Mercedes'],
    ['أوتوماتيك', 'Automatic'],
    ['يدوي', 'Manual'],
    ['فاخر', 'Luxury'],
    ['مقاعد', 'seats'],
    ['فطور', 'Breakfast'],
    ['قاعات', 'Halls'],
    ['جيم', 'Gym'],
    ['سبا', 'Spa'],
    ['مارينا', 'Marina'],
    ['واي‑فاي', 'Wi-Fi'],
    ['لا رحلات مباشرة على هذا المسار — نعرض كل الرحلات مرتّبة بالسعر', 'No direct flights on this route — showing all flights sorted by price'],
    ['لا عروض فعّالة حالياً', 'No active deals right now'],
    ['انسخ الكود', 'Copy code'],
    ['نُسخ الكود', 'Code copied'],
    ['الكود', 'Code'],
    ['كود خصم (اختياري', 'Promo code (optional'],
    ['تبدأ من', 'From'],
    ['خصم', 'off'],
    ['مسافر', 'traveler'],
    ['ليلة', 'night'],
    ['رحلة', 'Flight'],
    ['طيران', 'Flights'],
    ['فنادق', 'Hotels'],
    ['سيّارات', 'Cars'],
    ['العروض', 'Deals'],
    ['استكشف', 'Explore'],
    ['استكشاف', 'Explore'],
    ['يعمل حالياً ببيانات مبدئية', 'Currently running on seed data'],
    ['لتفعيل الجلب الحيّ اضبط', 'To enable live data set'],
    ['يرتدّ للبيانات المبدئية عند فشل الشبكة', 'falls back to seed data on network failure'],
    ['مربوط بـ', 'Connected to'],
    ['حيّ', 'live'],
    ['فعّال', 'Active'],
    ['الفعّالة', 'active'],
    ['تفعيل', 'Enable'],
    ['عملة', 'Currency'],

    // ── فعاليات وتذاكر ─────────────────────────────────────────────
    ['حفلات · رياضة · مؤتمرات · مسرح · ورش — تذاكرك بلمسة واحدة', 'Concerts · Sports · Conferences · Theater · Workshops — your tickets in one tap'],
    ['كل المناسبات في مكان واحد', 'All events in one place'],
    ['عِش اللحظة', 'Live the moment'],
    ['احجز تذكرتك', 'book your ticket'],
    ['ابحث عن حدث أو مكان', 'Search events or venues'],
    ['الأقرب تاريخاً', 'Soonest first'],
    ['لا مناسبات مطابقة للبحث', 'No events match your search'],
    ['لا مناسبات مطابقة', 'No matching events'],
    ['لا مناسبات بعد — أنشئ أولها', 'No events yet — create the first'],
    ['رجوع للمناسبات', 'Back to events'],
    ['إنشاء مناسبة', 'Create event'],
    ['اسم المناسبة', 'Event name'],
    ['القاعة/الملعب', 'Venue/stadium'],
    ['سعر التذكرة العادية', 'Standard ticket price'],
    ['عدد التذاكر', 'Ticket count'],
    ['نشر المناسبة', 'Publish event'],
    ['نُشرت المناسبة — ظهرت في الاستكشاف', 'Event published — now visible in Explore'],
    ['أكمل العنوان والسعر وعدد التذاكر', 'Enter the title, price, and ticket count'],
    ['كل المناسبات', 'All events'],
    ['المناسبات', 'Events'],
    ['مناسباتي', 'My events'],
    ['مناسبة من تنظيم', 'An event by'],
    ['مناسبة · بيع', 'event · sale'],
    ['بحث بالعنوان/المنظّم', 'Search by title/organizer'],
    ['أحدث المبيعات', 'Latest sales'],
    ['لا مبيعات بعد', 'No sales yet'],
    ['اسم المشترٍ', 'Buyer name'],
    ['أكمل اسم المشترٍ', 'Enter the buyer name'],
    ['لإرسال التذاكر', 'to send the tickets'],
    ['تأكيد وإصدار التذاكر', 'Confirm and issue tickets'],
    ['تمّ إصدار تذاكرك', 'Your tickets are issued'],
    ['لا تذاكر بعد — تصفّح «المناسبات» واحجز', 'No tickets yet — browse Events and book'],
    ['أُلغيت التذكرة واسترجعت المقاعد', 'Ticket cancelled and seats released'],
    ['إعادة المقاعد', 'Release seats'],
    ['اختر تذكرة واحدة على الأقل', 'Pick at least one ticket'],
    ['لم تختر تذاكر بعد', 'No tickets selected yet'],
    ['اختر تذاكرك', 'Pick your tickets'],
    ['لم يتبقَّ سوى', 'Only left:'],
    ['متبقّي', 'left:'],
    ['التذاكر المُباعة', 'Tickets sold'],
    ['تذاكري', 'My tickets'],
    ['تذاكر', 'Tickets'],
    ['تذكرة', 'ticket'],
    ['صالحة', 'Valid'],
    ['ليلة الطرب العربي', 'Arabic Music Night'],
    ['المسرح الكبير', 'Grand Theater'],
    ['أمسية غنائية استثنائية مع نخبة الفنانين وأوركسترا حيّة', 'An exceptional night with top artists and a live orchestra'],
    ['نهائي كأس المدينة', 'City Cup Final'],
    ['الملعب الأولمبي', 'Olympic Stadium'],
    ['المباراة النهائية المرتقبة — أجواء حماسية ومدرّجات كاملة', 'The long-awaited final — electric atmosphere, packed stands'],
    ['مؤتمر التقنية', 'Tech Conference'],
    ['مركز المؤتمرات', 'Convention Center'],
    ['ثلاثة أيّام من الجلسات وورش العمل مع روّاد التقنية', 'Three days of talks and workshops with tech leaders'],
    ['مسرحية «الرحلة', 'The Journey (Play'],
    ['مسرح الواجهة', 'Waterfront Theater'],
    ['عمل مسرحي كوميدي درامي يناسب العائلة', 'A comedy-drama stage play for the whole family'],
    ['ورشة التصوير الاحترافي', 'Pro Photography Workshop'],
    ['استوديو الضوء', 'Light Studio'],
    ['ورشة عملية ليوم كامل مع مدرّب معتمد — أدوات وشهادة', 'A full-day hands-on workshop with a certified trainer — gear and certificate'],
    ['حفلات موسيقية', 'Concerts'],
    ['ورش عمل', 'Workshops'],
    ['مؤتمرات', 'Conferences'],
    ['رياضة', 'Sports'],
    ['مسرح', 'Theater'],
    ['مدرّج عام', 'General stand'],
    ['الفئة الأولى', 'First class'],
    ['المقصورة', 'Box'],
    ['بلاتيني', 'Platinum'],
    ['أمامي', 'Front row'],
    ['حضور', 'Attendee'],
    ['محترف', 'Pro'],
    ['مقعد', 'Seat'],
    ['فئات', 'tiers'],
    ['شركة الفعّاليات', 'Events Co'],
    ['لوحة المنظّم', 'Organizer Panel'],
    ['المنظّمون', 'Organizers'],
    ['صفحة الحدث', 'Event page'],
    ['يُحدّد لاحقاً', 'TBA'],
    ['الملغاة', 'cancelled'],
    ['ملغاة', 'Cancelled'],
    ['ملغى', 'Cancelled'],
    ['كل المدن', 'All cities'],

    // ── تعليم (LMS) ────────────────────────────────────────────────
    ['دورات عملية بشهادات إتمام، ومتابعة لتقدّمك درساً بدرس', 'Practical courses with certificates, tracking your progress lesson by lesson'],
    ['تعلّم بوتيرتك', 'Learn at your pace'],
    ['مهارة جديدة', 'A new skill'],
    ['تبدأ اليوم', 'starts today'],
    ['ابحث عن دورة أو مدرّب', 'Search courses or instructors'],
    ['لا دورات مطابقة', 'No matching courses'],
    ['لا دورات بعد — أضف أولها', 'No courses yet — add the first'],
    ['اشترك مجاناً وابدأ التعلّم', 'Enroll free and start learning'],
    ['أنت مشترك بالفعل', 'You are already enrolled'],
    ['اشتركت في', 'Enrolled in'],
    ['أتممت الدورة! أحسنت', 'Course completed! Well done'],
    ['لم تشترك بعد — تصفّح «الدورات» وابدأ', 'Not enrolled yet — browse Courses and start'],
    ['اكتب عنوان الدورة', 'Enter the course title'],
    ['أُضيفت الدورة', 'Course added'],
    ['إضافة دورة', 'Add course'],
    ['عنوان الدورة', 'Course title'],
    ['إضافة درس', 'Add lesson'],
    ['عنوان الدرس', 'Lesson title'],
    ['المدة (دقائق', 'Duration (minutes'],
    ['أكمل العنوان والمدة', 'Enter the title and duration'],
    ['حفظ الدرس', 'Save lesson'],
    ['أُضيف الدرس', 'Lesson added'],
    ['لوحة المدرّب', 'Instructor Panel'],
    ['مدير الأكاديمية', 'Academy Admin'],
    ['أساسيات جافاسكربت', 'JavaScript Basics'],
    ['المتغيّرات', 'Variables'],
    ['الدوال', 'Functions'],
    ['مقدمة', 'Introduction'],
    ['تصميم واجهات', 'UI Design'],
    ['مبادئ التصميم', 'Design principles'],
    ['الألوان', 'Colors'],
    ['التسويق الرقمي', 'Digital Marketing'],
    ['وسائل التواصل', 'Social media'],
    ['أساسيات', 'Basics'],
    ['الإنجليزية للأعمال', 'Business English'],
    ['المراسلات', 'Correspondence'],
    ['الاجتماعات', 'Meetings'],
    ['أ. سارة', 'Ms. Sara'],
    ['أ. خالد', 'Mr. Khalid'],
    ['أ. منى', 'Ms. Mona'],
    ['أ. أحمد', 'Mr. Ahmed'],
    ['المشتركون', 'Enrolled'],
    ['مشترك', 'enrolled'],
    ['المدرّبون', 'Instructors'],
    ['المحتوى', 'Content'],
    ['الدورات', 'Courses'],
    ['دوراتي', 'My courses'],
    ['تعلّمي', 'My learning'],
    ['أكاديمية', 'Academy'],
    ['برمجة', 'Programming'],
    ['تصميم', 'Design'],
    ['تسويق', 'Marketing'],
    ['أعمال', 'Business'],
    ['لغات', 'Languages'],
    ['مبتدئ', 'Beginner'],
    ['متوسّط', 'Intermediate'],
    ['إتمام', 'Complete'],
    ['الدروس', 'Lessons'],
    ['دروس', 'lessons'],
    ['درس', 'lesson'],
    ['منشور', 'Published'],
    ['إخفاء', 'Hide'],
    ['نشر', 'Publish'],

    // ── مدرسة ──────────────────────────────────────────────────────
    ['جدولك ودرجاتك وواجباتك وإعلانات مدرستك — في مكان واحد', 'Your schedule, grades, homework, and school announcements — in one place'],
    ['بوّابتك الدراسية', 'Your school portal'],
    ['لوحة المعلّم', 'Teacher Panel'],
    ['إدارة المدرسة', 'School Administration'],
    ['الجدول الأسبوعي', 'Weekly schedule'],
    ['حصص اليوم', 'Today’s classes'],
    ['لا درجات مرصودة بعد', 'No grades recorded yet'],
    ['المعدّل العام', 'Overall average'],
    ['المعدّل', 'Average'],
    ['متوسّط الدرجات', 'Grade average'],
    ['لا واجبات حالياً', 'No homework right now'],
    ['أدخل درجة صحيحة', 'Enter a valid grade'],
    ['رُصدت درجة', 'Grade recorded for'],
    ['رصد درجة', 'Record grade'],
    ['الدرجة', 'Grade'],
    ['رصد', 'Record'],
    ['إضافة واجب', 'Add homework'],
    ['عنوان الواجب', 'Homework title'],
    ['اكتب عنوان الواجب', 'Enter the homework title'],
    ['أُضيف الواجب', 'Homework added'],
    ['نشر إعلان', 'Post announcement'],
    ['نص الإعلان', 'Announcement text'],
    ['اكتب نص الإعلان', 'Enter the announcement text'],
    ['نُشر الإعلان', 'Announcement posted'],
    ['الإعلانات المنشورة', 'Posted announcements'],
    ['لا إعلانات', 'No announcements'],
    ['الإعلانات', 'Announcements'],
    ['تمارين الفصل الثالث', 'Chapter 3 exercises'],
    ['تقرير عن الخلية', 'Report on the cell'],
    ['اجتماع أولياء الأمور الخميس القادم', 'Parent meeting next Thursday'],
    ['بداية الاختبارات الأسبوع المقبل', 'Exams start next week'],
    ['الرياضيات', 'Math'],
    ['العلوم', 'Science'],
    ['اللغة العربية', 'Arabic'],
    ['الإنجليزية', 'English'],
    ['الحاسب', 'Computer'],
    ['الرئيسية', 'Home'],
    ['الجدول', 'Schedule'],
    ['الدرجات', 'Grades'],
    ['درجاتي', 'My grades'],
    ['الواجبات', 'Homework'],
    ['الطلاب', 'Students'],
    ['المعلّم', 'Teacher'],
    ['المواد', 'Subjects'],
    ['الحصّة', 'Period'],
    ['مدرسة', 'School'],
    ['تسليم', 'due'],
    ['سالم', 'Salem'],
    ['نورة', 'Noura'],
    ['فهد', 'Fahd'],
    ['ليان', 'Layan'],

    // ── طقس/عملات (أدوات) ──────────────────────────────────────────
    ['اكتب اسم مدينة (مثل: الرياض، القاهرة، دبي', 'Type a city name (e.g. Riyadh, Cairo, Dubai'],
    ['اكتب اسم مدينة لعرض طقسها الحالي وتوقّعات الأسبوع', 'Type a city to see its current weather and weekly forecast'],
    ['اكتب اسم مدينة أولاً', 'Type a city name first'],
    ['جاري جلب الطقس لـ', 'Fetching weather for'],
    ['لم نعثر على', 'Could not find'],
    ['جرّب اسماً آخر', 'try another name'],
    ['تعذّر جلب الطقس الآن — حاول لاحقاً', 'Could not fetch weather — try again later'],
    ['مدن سريعة', 'Quick cities'],
    ['غائم جزئياً', 'Partly cloudy'],
    ['صافٍ غالباً', 'Mostly clear'],
    ['رذاذ خفيف', 'Light drizzle'],
    ['مطر خفيف', 'Light rain'],
    ['مطر غزير', 'Heavy rain'],
    ['عواصف رعدية', 'Thunderstorms'],
    ['غير معروف', 'Unknown'],
    ['زخّات', 'Showers'],
    ['صافٍ', 'Clear'],
    ['غائم', 'Cloudy'],
    ['ضباب', 'Fog'],
    ['ثلج', 'Snow'],
    ['مطر', 'Rain'],
    ['رياح', 'Wind'],
    ['الطقس', 'Weather'],
    ['طقس', 'Weather'],
    ['أسعار العملات الرقمية', 'Crypto Prices'],
    ['ابحث عن عملة', 'Search coins'],
    ['جاري تحديث الأسعار', 'Updating prices'],
    ['تعذّر جلب الأسعار الآن — اضغط «تحديث» للمحاولة', 'Could not fetch prices — press Refresh to retry'],
    ['لا نتائج للبحث', 'No search results'],
    ['لا بيانات بعد', 'No data yet'],
    ['القيمة السوقية', 'Market cap'],
    ['تحديث', 'Refresh'],
    ['محوّل العملات', 'Currency Converter'],
    ['اكتب مبلغاً واختر العملات ثم اضغط «تحويل', 'Enter an amount, pick currencies, then press Convert'],
    ['اكتب مبلغاً أكبر من صفر', 'Enter an amount above zero'],
    ['العملتان متطابقتان', 'Both currencies are the same'],
    ['جاري التحويل', 'Converting'],
    ['تعذّر جلب السعر الآن — حاول لاحقاً', 'Could not fetch the rate — try again later'],
    ['جاري جلب الأسعار', 'Fetching rates'],
    ['لا أسعار متاحة الآن', 'No rates available right now'],
    ['أسعار مقابل', 'Rates vs'],
    ['دولار أمريكي', 'US Dollar'],
    ['جنيه إسترليني', 'British Pound'],
    ['ريال سعودي', 'Saudi Riyal'],
    ['درهم إماراتي', 'UAE Dirham'],
    ['جنيه مصري', 'Egyptian Pound'],
    ['ين ياباني', 'Japanese Yen'],
    ['ليرة تركية', 'Turkish Lira'],
    ['دينار كويتي', 'Kuwaiti Dinar'],
    ['ريال قطري', 'Qatari Riyal'],
    ['يوان صيني', 'Chinese Yuan'],
    ['فرنك سويسري', 'Swiss Franc'],
    ['يورو', 'Euro'],
    ['تبديل', 'Swap'],
    ['تحويل', 'Convert'],
    ['عملات', 'Currencies'],
    ['بحث', 'Search'],

    // ── مدن وأيام وعموميات ─────────────────────────────────────────
    ['الرياض', 'Riyadh'],
    ['جدة', 'Jeddah'],
    ['الدمام', 'Dammam'],
    ['دبي', 'Dubai'],
    ['القاهرة', 'Cairo'],
    ['إسطنبول', 'Istanbul'],
    ['أبها', 'Abha'],
    ['الأحد', 'Sun'],
    ['الإثنين', 'Mon'],
    ['الثلاثاء', 'Tue'],
    ['الأربعاء', 'Wed'],
    ['الخميس', 'Thu'],
    ['الجمعة', 'Fri'],
    ['السبت', 'Sat'],
    ['لوحة الإدارة', 'Admin Panel'],
    ['لوحة المدير', 'Admin Panel'],
    ['الإدارة', 'Admin'],
    ['اللوحة', 'Panel'],
    ['المدير', 'Admin'],
    ['مدير المنصّة', 'Platform Admin'],
    ['مكتملة', 'Completed'],
    ['مكتمل', 'Completed'],
    ['إلغاء', 'Cancel'],
    ['حذف', 'Delete'],
    ['إضافة', 'Add'],
    ['إيقاف', 'Stop'],
    ['موقوف', 'Stopped'],
    ['الكل', 'All'],
    ['جديد', 'New'],
    ['عادي', 'Standard'],
    ['يوم', 'day'],
    ['أضف', 'Add'],
    ['اسمك', 'Your name'],
    ['المدينة', 'City'],
    ['المكان', 'Venue'],
    ['العنوان', 'Address'],
    ['التاريخ', 'Date'],
    ['الرمز', 'Icon'],
    ['رمز', 'Icon'],
    ['مثال', 'e.g'],
    ['البريد / الجوّال', 'Email / phone'],
    ['دعم', 'Support'],
    ['العميل', 'Customer'],
    ['الطالب', 'Student'],
    ['طلب', 'Order'],
    ['منتج', 'item'],
    ['من', 'From'],
    ['إلى', 'To'],
    ['في', 'in'],
    [' ﷼', ' SAR'],
    ['﷼', 'SAR'],
    // ── 🏭 jaola-erp: نظام إدارة المنشأة ─────────────────────────────
    ['منصرفات · إنتاج · مبيعات وفواتير · مخزون · تقارير — في مكان واحد.', 'Expenses · Production · Sales and invoices · Inventory · Reports — all in one place.'],
    ['تجريبياً: كلمة المرور «admin» لكل الأدوار — غيّرها من الإعدادات.', 'Demo: password is admin for all roles — change it in Settings.'],
    ['الإيراد مقابل المنصرف — آخر ٦ أشهر', 'Revenue vs expenses — last 6 months'],
    ['لا أصناف بعد — أضف أول صنف من الأعلى.', 'No items yet — add your first item above.'],
    ['لا تنبيهات — المخزون فوق حدود الأمان ✅', 'No alerts — inventory is above safe levels ✅'],
    ['ملاحظة (خط الإنتاج، الوردية…)', 'Note (line, shift...)'],
    ['البيان (كهرباء، رواتب…)', 'Description (electricity, salaries...)'],
    ['الوحدة (كرتونة/قطعة)', 'Unit (box/piece)'],
    ['أضف بنداً واحداً على الأقل', 'Add at least one line'],
    ['الكمية لم تعد متاحة:', 'Quantity no longer available:'],
    ['الكمية أكبر من المتاح', 'Quantity exceeds available'],
    ['اتركها فارغة للإبقاء', 'Leave empty to keep current'],
    ['شكراً لتعاملكم معنا', 'Thank you for your business'],
    ['نظام إدارة المنشأة', 'Facility Management System'],
    ['سُجّلت دفعة الإنتاج', 'Production batch recorded'],
    ['اختر الصنف والكمية', 'Pick the item and quantity'],
    ['اكتب البيان والمبلغ', 'Enter description and amount'],
    ['مبيعات آخر ٧ أيام', 'Sales — last 7 days'],
    ['ربح الشهر التقريبي', 'Approx. month profit'],
    ['صُدّرت المنصرفات CSV', 'Expenses exported to CSV'],
    ['صُدّرت المبيعات CSV', 'Sales exported to CSV'],
    ['تنبيهات المخزون', 'Inventory alerts'],
    ['تسجيل دفعة إنتاج', 'Record production batch'],
    ['المبيعات والفواتير', 'Sales and invoices'],
    ['كلمة المرور غير صحيحة', 'Incorrect password'],
    ['كلمة المرور الجديدة', 'New password'],
    ['اكتب اسم الصنف', 'Enter item name'],
    ['لا دفعات إنتاج بعد.', 'No production batches yet.'],
    ['لا منصرفات مسجّلة.', 'No expenses recorded.'],
    ['لا فواتير بعد.', 'No invoices yet.'],
    ['حُفظت الإعدادات', 'Settings saved'],
    ['حُفظت الفاتورة', 'Invoice saved'],
    ['سُجّل المنصرف', 'Expense recorded'],
    ['تسجيل منصرف', 'Record expense'],
    ['منصرفات اليوم', 'Expenses today'],
    ['منصرف الشهر', 'Month expenses'],
    ['المنصرفات', 'Expenses'],
    ['منشأة jaola', 'jaola Facility'],
    ['اسم المنشأة', 'Facility name'],
    ['أمين المخزن', 'Storekeeper'],
    ['أمين مخزن', 'Storekeeper'],
    ['حفظ الفاتورة', 'Save invoice'],
    ['فاتورة جديدة', 'New invoice'],
    ['أضف البند', 'Add line'],
    ['اسم العميل', 'Customer name'],
    ['عميل نقدي', 'Cash customer'],
    ['حفظ الإعدادات', 'Save settings'],
    ['أصناف المخزون', 'Inventory items'],
    ['مبيعات اليوم', 'Sales today'],
    ['مبيعات الشهر', 'Month sales'],
    ['إيراد الشهر', 'Month revenue'],
    ['صافي الشهر', 'Month net'],
    ['عدد الفواتير', 'Invoice count'],
    ['الكمية المنتجة', 'Produced quantity'],
    ['إضافة صنف', 'Add item'],
    ['أُضيف الصنف', 'Item added'],
    ['حُذف الصنف', 'Item deleted'],
    ['اسم الصنف', 'Item name'],
    ['حد التنبيه', 'Alert level'],
    ['سعر البيع', 'Sale price'],
    ['لوحة اليوم', 'Today board'],
    ['المنتج الأول', 'First product'],
    ['المنتج الثاني', 'Second product'],
    ['المنتج الثالث', 'Third product'],
    ['المتبقي', 'remaining'],
    ['الإجمالي:', 'Total:'],
    ['الإجمالي', 'Total'],
    ['فاتورة #', 'Invoice #'],
    ['العميل:', 'Customer:'],
    ['المحاسب', 'Accountant'],
    ['محاسب', 'Accountant'],
    ['المالك', 'Owner'],
    ['مالك', 'Owner'],
    ['اللوحة', 'Board'],
    ['طباعة', 'Print'],
    ['التكلفة', 'Cost'],
    ['كرتونة', 'Box'],
    ['قطعة', 'Piece'],
    ['وحدة', 'Unit'],
    ['الوحدة', 'Unit'],
    ['البيان', 'Description'],
    ['الفئة', 'Category'],
    ['المبلغ', 'Amount'],
    ['تشغيل', 'Operations'],
    ['رواتب', 'Salaries'],
    ['خامات', 'Materials'],
    ['صيانة', 'Maintenance'],
    ['نقل', 'Transport'],
    ['أخرى', 'Other'],
    ['العملة', 'Currency'],
    ['متاح:', 'available:'],
    ['البنود', 'Lines'],
    ['بند', 'line'],
    ['الحد', 'min'],
    ['الدور', 'Role'],
    ['مرحباً', 'Welcome'],
    ['رقم', 'No.'],
    ['منصرفات CSV', 'Expenses CSV'],
    ['مبيعات CSV', 'Sales CSV'],
    ['الإعدادات', 'Settings'],
    ['إعدادات', 'Settings'],
    ['التقارير', 'Reports'],
    ['تقارير', 'Reports'],
    ['الفواتير', 'Invoices'],
    ['الإنتاج', 'Production'],
    ['إنتاج', 'Production'],
    ['الكمية', 'Quantity'],
    ['كمية', 'Quantity'],
    ['ر.س', 'SAR'],
    ['مرضى · مواعيد · زيارات ووصفات · فواتير كشف · تقارير.', 'Patients · Appointments · Visits and prescriptions · Consultation invoices · Reports.'],
    ['موظفون · حضور · إجازات · رواتب بقسائم.', 'Employees · Attendance · Leaves · Payroll with payslips.'],
    ['بيع سريع · إيصال حراري · إغلاق وردية · تقارير.', 'Fast sell · Thermal receipt · Shift close · Reports.'],
    ['طاولات · طلبات · شاشة مطبخ · فواتير · تقارير.', 'Tables · Orders · Kitchen display · Bills · Reports.'],
    ['الإغلاق يصفّر عدّادات الوردية ويحفظ ملخّصها في التقارير.', 'Closing resets the shift counters and saves its summary to reports.'],
    ['حفظ الزيارة وإصدار الفاتورة', 'Save visit and issue invoice'],
    ['الوصفة (دواء وجرعة في كل سطر)', 'Prescription (one drug and dose per line)'],
    ['ملاحظة (حساسية، أمراض مزمنة…)', 'Note (allergy, chronic conditions...)'],
    ['هذه قسيمة رسمية صادرة من نظام الموارد البشرية', 'Official payslip issued by the HR system'],
    ['مسجّل حضوره اليوم بالفعل', 'Already checked in today'],
    ['نظام إدارة العيادة', 'Clinic Management System'],
    ['نظام الموارد البشرية', 'HR System'],
    ['نظام نقطة البيع', 'Point of Sale System'],
    ['نظام تشغيل المطعم', 'Restaurant Operations System'],
    ['الحضور والانصراف', 'Attendance'],
    ['الحاضرون اليوم', 'Present today'],
    ['حاضرون اليوم', 'Present today'],
    ['رسوم الكشف: ', 'Consultation fee: '],
    ['رسوم الكشف', 'Consultation fee'],
    ['رسوم الكشف', 'Fee'],
    ['الزيارات والوصفات', 'Visits and prescriptions'],
    ['سجل الزيارات', 'Visit log'],
    ['زيارة جديدة', 'New visit'],
    ['اسم المريض', 'Patient name'],
    ['اسم العيادة', 'Clinic name'],
    ['اسم الطبيب', 'Doctor name'],
    ['المريض الأول', 'First patient'],
    ['المريضة الثانية', 'Second patient'],
    ['حساسية بنسلين', 'Penicillin allergy'],
    ['سبب الزيارة', 'Visit reason'],
    ['إجمالي المرضى', 'Total patients'],
    ['زيارات اليوم', 'Visits today'],
    ['زيارات الشهر', 'Visits this month'],
    ['إجمالي الزيارات', 'Total visits'],
    ['مواعيد اليوم', 'Today appointments'],
    ['حجز موعد', 'Book appointment'],
    ['إضافة مريض', 'Add patient'],
    ['أُضيف المريض', 'Patient added'],
    ['اكتب اسم المريض', 'Enter patient name'],
    ['لا مرضى بعد.', 'No patients yet.'],
    ['لا مواعيد اليوم.', 'No appointments today.'],
    ['لا مواعيد بعد.', 'No appointments yet.'],
    ['لا زيارات بعد.', 'No visits yet.'],
    ['اختر المريض', 'Pick the patient'],
    ['حُجز الموعد', 'Appointment booked'],
    ['حُفظت الزيارة', 'Visit saved'],
    ['سلامتك تهمّنا', 'Your wellbeing matters to us'],
    ['صُدّرت الزيارات CSV', 'Visits exported to CSV'],
    ['الزيارات CSV', 'Visits CSV'],
    ['رسوم الكشف', 'Fee'],
    ['التشخيص:', 'Diagnosis:'],
    ['التشخيص', 'Diagnosis'],
    ['الوصفة:', 'Prescription:'],
    ['الوصفة', 'Prescription'],
    ['المريض:', 'Patient:'],
    ['المرضى', 'Patients'],
    ['المريض', 'Patient'],
    ['مرضى', 'Patients'],
    ['الطبيب', 'Doctor'],
    ['الاستقبال', 'Reception'],
    ['العيادة', 'Clinic'],
    ['عيادة', 'Clinic'],
    ['الهاتف', 'Phone'],
    ['العمر', 'Age'],
    ['الجنس', 'Gender'],
    ['ذكر', 'Male'],
    ['أنثى', 'Female'],
    ['الموارد البشرية', 'Human Resources'],
    ['الراتب الأساسي', 'Base salary'],
    ['بدلات/مكافأة', 'Allowances/bonus'],
    ['إصدار قسيمة راتب', 'Issue payslip'],
    ['المسمّى الوظيفي', 'Job title'],
    ['الحاضرون', 'Present'],
    ['حاضرون', 'Present'],
    ['الموظفون', 'Employees'],
    ['موظفون', 'Employees'],
    ['اسم الشركة', 'Company name'],
    ['الموظف الأول', 'First employee'],
    ['الموظفة الثانية', 'Second employee'],
    ['إجمالي الموظفين', 'Total employees'],
    ['كتلة الرواتب', 'Payroll mass'],
    ['إجازات معلّقة', 'Pending leaves'],
    ['طلب إجازة', 'Request leave'],
    ['تسجيل حضور اليوم', 'Check in today'],
    ['تسجيل انصراف', 'Check out'],
    ['إضافة موظف', 'Add employee'],
    ['أُضيف الموظف', 'Employee added'],
    ['اكتب اسم الموظف', 'Enter employee name'],
    ['لا موظفين بعد.', 'No employees yet.'],
    ['لا سجل حضور بعد.', 'No attendance yet.'],
    ['لا حضور مسجّل اليوم.', 'No attendance recorded today.'],
    ['اختر الموظف والتواريخ', 'Pick employee and dates'],
    ['اختر الموظف', 'Pick the employee'],
    ['سُجّل الحضور', 'Check-in recorded'],
    ['سُجّل الانصراف', 'Check-out recorded'],
    ['لا حضور مسجّل اليوم', 'No check-in today'],
    ['قُدّم طلب الإجازة', 'Leave request submitted'],
    ['تمت الموافقة', 'Approved'],
    ['رُفض الطلب', 'Request rejected'],
    ['قسيمة راتب', 'Payslip'],
    ['صافي الراتب:', 'Net salary:'],
    ['بدلات ومكافآت', 'Allowances and bonuses'],
    ['صدرت قسيمة راتب', 'Payslip issued for'],
    ['لا طلبات إجازة بعد.', 'No leave requests yet.'],
    ['لا قسائم بعد.', 'No payslips yet.'],
    ['موافَق', 'Approved'],
    ['معلّق', 'Pending'],
    ['المسمّى', 'Title'],
    ['القسم', 'Department'],
    ['الراتب', 'Salary'],
    ['المالية', 'Finance'],
    ['التسويق', 'Marketing'],
    ['محاسب', 'Accountant'],
    ['مسوّقة', 'Marketer'],
    ['الموظف', 'Employee'],
    ['موظف', 'Employee'],
    ['المدير', 'Manager'],
    ['مدير', 'Manager'],
    ['حضور', 'In'],
    ['انصراف', 'Out'],
    ['من', 'From'],
    ['إلى', 'To'],
    ['بيع سريع · إيصال حراري · إغلاق وردية · تقارير.', 'Fast sell · Thermal receipt · Shift close · Reports.'],
    ['الوردية والإغلاق', 'Shift and close'],
    ['ورديات سابقة', 'Previous shifts'],
    ['🔒 إغلاق الوردية الآن', '🔒 Close shift now'],
    ['فواتير الوردية', 'Shift invoices'],
    ['تحصيل نقدي', 'Cash collected'],
    ['تحصيل شبكة', 'Card collected'],
    ['إجمالي الوردية', 'Shift total'],
    ['وقت الإغلاق', 'Close time'],
    ['لا مبيعات في الوردية الحالية', 'No sales in the current shift'],
    ['أُغلقت الوردية — إجمالي', 'Shift closed — total'],
    ['لا ورديات مغلقة بعد.', 'No closed shifts yet.'],
    ['اضغط منتجاً لإضافته للسلة.', 'Tap a product to add it to the cart.'],
    ['تفريغ السلة', 'Clear cart'],
    ['السلة فارغة', 'Cart is empty'],
    ['رمز (اختياري) 🥤', 'Emoji (optional) 🥤'],
    ['اسم المتجر', 'Store name'],
    ['اسم المنتج', 'Product name'],
    ['اضغط منتجاً', 'Tap a product'],
    ['شكراً لزيارتكم', 'Thank you for visiting'],
    ['طريقة الدفع', 'Payment method'],
    ['نقدي', 'Cash'],
    ['شبكة', 'Card'],
    ['السلة', 'Cart'],
    ['قهوة', 'Coffee'],
    ['شاي', 'Tea'],
    ['عصير', 'Juice'],
    ['ماء', 'Water'],
    ['كيك', 'Cake'],
    ['ساندويتش', 'Sandwich'],
    ['نظام تشغيل المطعم', 'Restaurant Ops System'],
    ['قائمة الطعام', 'Menu'],
    ['شاشة المطبخ (KDS)', 'Kitchen Display (KDS)'],
    ['أرسل للمطبخ', 'Send to kitchen'],
    ['📨 أرسل للمطبخ', '📨 Send to kitchen'],
    ['🧾 إغلاق وفاتورة', '🧾 Close and bill'],
    ['طلب الطاولة', 'Table order'],
    ['أخذ طلب', 'Take order'],
    ['عدد الطاولات', 'Tables count'],
    ['اسم المطعم', 'Restaurant name'],
    ['اسم الصنف', 'Item name'],
    ['برجر لحم', 'Beef burger'],
    ['بيتزا', 'Pizza'],
    ['دجاج مشوي', 'Grilled chicken'],
    ['سلطة', 'Salad'],
    ['بطاطس', 'Fries'],
    ['مشروب', 'Drink'],
    ['برجر', 'Burger'],
    ['لا طلبات في المطبخ الآن.', 'No orders in the kitchen now.'],
    ['اضغط صنفاً لإضافته.', 'Tap an item to add it.'],
    ['أُرسل طلب طاولة', 'Sent order for table'],
    ['للمطبخ', 'to kitchen'],
    ['الطلب فارغ', 'Order is empty'],
    ['لا طلب على هذه الطاولة', 'No order on this table'],
    ['أُغلقت طاولة', 'Closed table'],
    ['لا صنف على', 'No item on'],
    ['اكتب اسم الصنف', 'Enter item name'],
    ['أُضيف الصنف', 'Item added'],
    ['أُضيف المنتج', 'Product added'],
    ['اكتب اسم المنتج', 'Enter product name'],
    ['لا أصناف بعد.', 'No items yet.'],
    ['لا منتجات بعد.', 'No products yet.'],
    ['متاحة', 'Free'],
    ['طاولة', 'Table'],
    ['الطاولات', 'Tables'],
    ['المطبخ', 'Kitchen'],
    ['النادل', 'Waiter'],
    ['نادل', 'Waiter'],
    ['الكاشير', 'Cashier'],
    ['كاشير', 'Cashier'],
    ['الوردية', 'Shift'],
    ['القائمة', 'Menu'],
    ['البيع', 'Sell'],
    ['جديد', 'New'],
    ['تحضير', 'Preparing'],
    ['جاهز', 'Ready'],
    ['اكتمل ✅', 'Done ✅'],
    ['المنتج', 'Product'],
    ['الصنف', 'Item'],
    ['فاتورة كشف', 'Consultation invoice'],
    ['صُدّرت الفواتير CSV', 'Bills exported to CSV'],
    ['الفواتير CSV', 'Bills CSV'],
    ['فواتير اليوم', 'Bills today'],
    ['طلب طاولة', 'Order table'],
    ['ذكر', 'Male'],
    ['الشركة', 'Company'],
    ['المتجر', 'Store'],
    ['المطعم', 'Restaurant'],
    ['الطلب', 'Order'],
    ['ر.س', 'SAR'],

    ['لكل الأدوار', 'for all roles'],
    ['د. جاولا', 'Dr. Jaola'],
    ['إيراد آخر ٧ أيام', 'Revenue — last 7 days'],
    ['آخر ٧ أيام', 'last 7 days'],
    ['الزيارات', 'Visits'],
    ['الإجازات', 'Leaves'],
    ['القسيمة', 'Payslip'],
    ['الحالة', 'Status'],
    ['الرسوم', 'Fee'],
    ['الفاتورة', 'Invoice'],
    ['الأساسي', 'Base'],
    ['الصافي', 'Net'],
    ['موافقة', 'Approve'],
    ['مرفوض', 'Rejected'],
    ['خصومات', 'Deductions'],
    ['بدلات', 'Allowances'],
    ['الاسم', 'Name'],
    ['السبب', 'Reason'],
    ['ملاحظة', 'Note'],
    ['الشهر', 'Month'],
    ['شركة', 'Company'],
    ['رفض', 'Reject'],
    ['شهر', 'month'],
    ['عام', 'General'],
    ['ر.س', 'SAR'],
    // ── 💊 pharmacy / 🏢 property / 🎬 cinema ──
    ['أدوية · صرف بوصفة · تنبيه نفاد وانتهاء صلاحية · تقارير.', 'Medicines · Prescription dispensing · Low-stock and expiry alerts · Reports.'],
    ['وحدات · عقود · تحصيل إيجار · تنبيه استحقاق · تقارير.', 'Units · Contracts · Rent collection · Due alerts · Reports.'],
    ['أحدث الأفلام · اختر مقعدك · تذكرة فورية.', 'Latest movies · Pick your seat · Instant ticket.'],
    ['أيام التنبيه قبل انتهاء الصلاحية', 'Alert days before expiry'],
    ['⏳ قرب/انتهاء الصلاحية', '⏳ Near/expired'],
    ['قرب/انتهاء الصلاحية', 'Near/expired'],
    ['⏳ إيجارات مستحقّة/متأخّرة', '⏳ Due/overdue rents'],
    ['إيجارات مستحقّة/متأخّرة', 'Due/overdue rents'],
    ['صرف وإصدار إيصال', 'Dispense and issue receipt'],
    ['نظام إدارة الصيدلية', 'Pharmacy Management System'],
    ['نظام إدارة العقارات', 'Property Management System'],
    ['المستأجرون والعقود', 'Tenants and contracts'],
    ['تحصيل وإصدار إيصال', 'Collect and issue receipt'],
    ['كل إيجارات الشهر محصّلة ✅', 'All this month rents are collected ✅'],
    ['تحصيل آخر ٦ أشهر', 'Collection — last 6 months'],
    ['اسم الدواء', 'Medicine name'],
    ['اسم الصيدلية', 'Pharmacy name'],
    ['أصناف الأدوية', 'Medicine items'],
    ['سجل الصرف', 'Dispense log'],
    ['صرف جديد', 'New dispensing'],
    ['تاريخ الصلاحية', 'Expiry date'],
    ['حد التنبيه', 'Alert level'],
    ['سعر البيع', 'Sale price'],
    ['باراسيتامول', 'Paracetamol'],
    ['أموكسيسيلين', 'Amoxicillin'],
    ['شراب سعال', 'Cough syrup'],
    ['تنبيهات نفاد', 'Low-stock alerts'],
    ['قرب الانتهاء', 'Near expiry'],
    ['المخزون فوق الحدود ✅', 'Stock above thresholds ✅'],
    ['لا أدوية قرب الانتهاء ✅', 'No medicines near expiry ✅'],
    ['منتهٍ منذ', 'expired since'],
    ['ينتهي خلال', 'expires in'],
    ['لا أدوية بعد.', 'No medicines yet.'],
    ['اكتب اسم الدواء', 'Enter medicine name'],
    ['أُضيف الدواء', 'Medicine added'],
    ['اختر الدواء والكمية', 'Pick medicine and quantity'],
    ['أضف صنفاً واحداً على الأقل', 'Add at least one item'],
    ['الكمية لم تعد متاحة:', 'Quantity no longer available:'],
    ['تم الصرف', 'Dispensed'],
    ['إيصال صرف', 'Dispense receipt'],
    ['سلامتكم أمانة', 'Your safety is our trust'],
    ['عمليات صرف اليوم', 'Dispenses today'],
    ['إجمالي الصرف', 'Total dispenses'],
    ['اسم الدواء', 'Medicine'],
    ['الأدوية', 'Medicines'],
    ['الدواء', 'Medicine'],
    ['دواء', 'Medicine'],
    ['الصرف', 'Dispensing'],
    ['صرف', 'Dispense'],
    ['الصلاحية', 'Expiry'],
    ['منتهٍ', 'Expired'],
    ['الصيدلي', 'Pharmacist'],
    ['صيدلي', 'Pharmacist'],
    ['الصيدلية', 'Pharmacy'],
    ['صيدلية', 'Pharmacy'],
    ['نفاد المخزون', 'Low stock'],
    ['نفاد', 'Low'],
    ['اسم/رقم الوحدة', 'Unit name/number'],
    ['النوع (شقة/محل/مكتب)', 'Type (apartment/shop/office)'],
    ['الإيجار الشهري', 'Monthly rent'],
    ['اسم المستأجر', 'Tenant name'],
    ['بداية العقد', 'Contract start'],
    ['مدة العقد (شهر)', 'Contract duration (months)'],
    ['إنشاء عقد', 'Create contract'],
    ['تحصيل الإيجار', 'Rent collection'],
    ['اسم المكتب', 'Office name'],
    ['مكتب jaola العقاري', 'jaola Real Estate Office'],
    ['إجمالي الوحدات', 'Total units'],
    ['مؤجّرة', 'Rented'],
    ['مستحقّة هذا الشهر', 'Due this month'],
    ['تحصيل الشهر', 'Month collection'],
    ['الإيجار المتوقّع', 'Expected rent'],
    ['نسبة الإشغال', 'Occupancy'],
    ['إجمالي العقود', 'Total contracts'],
    ['لا وحدات بعد.', 'No units yet.'],
    ['اكتب اسم الوحدة', 'Enter unit name'],
    ['أُضيفت الوحدة', 'Unit added'],
    ['لا وحدات شاغرة', 'No vacant units'],
    ['لا عقود بعد.', 'No contracts yet.'],
    ['اكتب الاسم واختر وحدة شاغرة', 'Enter name and pick a vacant unit'],
    ['الوحدة غير متاحة', 'Unit unavailable'],
    ['أُنشئ العقد', 'Contract created'],
    ['أُنهي العقد', 'Contract ended'],
    ['لا تحصيل بعد.', 'No collections yet.'],
    ['اختر العقد', 'Pick the contract'],
    ['محصّل بالفعل عن', 'Already collected for'],
    ['حُصّل الإيجار', 'Rent collected'],
    ['إيصال إيجار', 'Rent receipt'],
    ['المبلغ المحصّل:', 'Amount collected:'],
    ['شكراً لالتزامكم', 'Thank you for your commitment'],
    ['صُدّر التحصيل CSV', 'Collections exported to CSV'],
    ['التحصيل CSV', 'Collections CSV'],
    ['اسم/رقم الوحدة', 'Unit'],
    ['المستأجرون', 'Tenants'],
    ['المستأجر:', 'Tenant:'],
    ['المستأجر', 'Tenant'],
    ['مستأجر', 'Tenant'],
    ['الوحدات', 'Units'],
    ['الوحدة:', 'Unit:'],
    ['الوحدة', 'Unit'],
    ['وحدة', 'unit'],
    ['التحصيل', 'Collection'],
    ['تحصيل', 'Collect'],
    ['العقد', 'Contract'],
    ['شاغرة', 'Vacant'],
    ['الإيجار', 'Rent'],
    ['شقة', 'Apartment'],
    ['محل', 'Shop'],
    ['مكتب', 'Office'],
    ['عن شهر:', 'For month:'],
    ['عن شهر', 'For month'],
    ['المبلغ المحصّل', 'Collected'],
    ['المكتب العقاري', 'Real Estate Office'],
    ['العقارات', 'Properties'],
    ['احجز تذكرتك الآن', 'Book your ticket now'],
    ['احجز تذكرتك', 'Book your ticket'],
    ['يُعرض الآن', 'Now showing'],
    ['اختر مقاعدك', 'Choose your seats'],
    ['اختر مقعدك', 'pick your seat'],
    ['دخول الإدارة', 'Admin login'],
    ['المهمة الأخيرة', 'The Last Mission'],
    ['قلوب لا تنسى', 'Unforgettable Hearts'],
    ['كوكب المغامرة', 'Adventure Planet'],
    ['التصنيف (أكشن/دراما)', 'Genre (action/drama)'],
    ['سعر التذكرة', 'Ticket price'],
    ['اسم الفيلم', 'Movie name'],
    ['إضافة فيلم', 'Add movie'],
    ['إضافة عرض', 'Add showtime'],
    ['القاعة (1/2/VIP)', 'Hall (1/2/VIP)'],
    ['اختر مقعداً واحداً على الأقل', 'Pick at least one seat'],
    ['اختر مقاعدك أولاً', 'Pick your seats first'],
    ['أحد المقاعد حُجز للتو', 'A seat was just booked'],
    ['لا عروض لهذا الفيلم بعد.', 'No showtimes for this movie yet.'],
    ['لا تذاكر بعد — احجز من صفحة الأفلام.', 'No tickets yet — book from the movies page.'],
    ['استمتع بالمشاهدة', 'Enjoy the show'],
    ['مرحباً بالإدارة', 'Welcome, admin'],
    ['طباعة التذكرة', 'Print ticket'],
    ['لا أفلام حالياً.', 'No movies now.'],
    ['لا أفلام بعد.', 'No movies yet.'],
    ['اكتب اسم الفيلم', 'Enter movie name'],
    ['أُضيف الفيلم', 'Movie added'],
    ['أُضيف العرض', 'Showtime added'],
    ['اختر الفيلم', 'Pick the movie'],
    ['مقعد متاح', 'seats available'],
    ['مقعد', 'seat'],
    ['مقاعد', 'seats'],
    ['أكشن', 'Action'],
    ['دراما', 'Drama'],
    ['مغامرة', 'Adventure'],
    ['التذكرة', 'Ticket'],
    ['تذكرتي', 'My ticket'],
    ['تذاكري', 'My tickets'],
    ['تذكرة', 'Ticket'],
    ['الأفلام', 'Movies'],
    ['الفيلم', 'Movie'],
    ['فيلم', 'Movie'],
    ['العروض', 'Showtimes'],
    ['عرض', 'Show'],
    ['القاعة', 'Hall'],
    ['قاعة', 'Hall'],
    ['الشاشة', 'Screen'],
    ['مختار', 'Selected'],
    ['متاح', 'Available'],
    ['اختياري', 'optional'],
    ['يُعرض', 'Showing'],
    ['ر.س', 'SAR'],
    ['سينما jaola', 'jaola Cinema'],
    ['سينما', 'Cinema'],
    ['ر.س', 'SAR'],
    // ── 🔧 workshop / 💪 gym ──
    ['عملاء وسيارات · بطاقات عمل · خدمات وقطع · فواتير · تقارير.', 'Customers and cars · Job cards · Services and parts · Invoices · Reports.'],
    ['باقات مرنة · حصص جماعية · مدرّبون معتمدون.', 'Flexible plans · Group classes · Certified coaches.'],
    ['نظام إدارة الورشة', 'Workshop Management System'],
    ['بطاقات قيد العمل', 'Jobs in progress'],
    ['العملاء والسيارات', 'Customers and cars'],
    ['السيارة (نوع/موديل)', 'Car (make/model)'],
    ['فتح بطاقة عمل', 'Open job card'],
    ['بطاقة عمل', 'Job card'],
    ['بطاقات العمل', 'Job cards'],
    ['إضافة بند (خدمة/قطعة)', 'Add item (service/part)'],
    ['الوصف (تغيير زيت / فلتر…)', 'Description (oil change / filter...)'],
    ['فاتورة إصلاح', 'Repair invoice'],
    ['اسم الورشة', 'Workshop name'],
    ['بطاقات مفتوحة', 'Open jobs'],
    ['جاهزة للتسليم', 'Ready for delivery'],
    ['إجمالي العملاء', 'Total customers'],
    ['لا بطاقات مفتوحة ✅', 'No open jobs ✅'],
    ['العميل الأول', 'First customer'],
    ['العميل الثاني', 'Second customer'],
    ['تويوتا كامري', 'Toyota Camry'],
    ['نيسان باترول', 'Nissan Patrol'],
    ['اسم العميل', 'Customer name'],
    ['لا عملاء بعد.', 'No customers yet.'],
    ['اكتب اسم العميل', 'Enter customer name'],
    ['أُضيف العميل', 'Customer added'],
    ['لا بطاقات بعد.', 'No job cards yet.'],
    ['فُتحت بطاقة', 'Opened card'],
    ['لا بنود بعد.', 'No items yet.'],
    ['اكتب الوصف', 'Enter description'],
    ['البطاقة مُسلّمة بالفعل', 'Card already delivered'],
    ['شكراً لثقتكم بنا', 'Thank you for your trust'],
    ['بطاقات هذا الشهر', 'Cards this month'],
    ['إيراد الشهر (مُسلّمة)', 'Month revenue (delivered)'],
    ['إجمالي المُسلّمة', 'Total delivered'],
    ['إجمالي البطاقات', 'Total cards'],
    ['صُدّرت البطاقات CSV', 'Job cards exported to CSV'],
    ['البطاقات CSV', 'Cards CSV'],
    ['قيد الإصلاح', 'Repairing'],
    ['بالانتظار', 'Waiting'],
    ['مُسلّمة', 'Delivered'],
    ['جاهزة', 'Ready'],
    ['بطاقة عمل #', 'Job card #'],
    ['العطل:', 'Complaint:'],
    ['العطل/الطلب', 'Complaint/request'],
    ['العطل', 'Complaint'],
    ['السيارة:', 'Car:'],
    ['السيارة', 'Car'],
    ['اللوحة', 'Plate'],
    ['الفنّي', 'Technician'],
    ['فنّي', 'Technician'],
    ['الورشة', 'Workshop'],
    ['ورشة', 'Workshop'],
    ['البطاقات', 'Cards'],
    ['العملاء', 'Customers'],
    ['ابدأ رحلتك نحو لياقتك', 'Start your fitness journey'],
    ['باقات الاشتراك', 'Membership plans'],
    ['جدول الحصص', 'Class schedule'],
    ['إتمام الاشتراك', 'Complete signup'],
    ['تأكيد الاشتراك', 'Confirm signup'],
    ['اسم الباقة', 'Plan name'],
    ['المزايا (يفصلها ,)', 'Perks (comma-separated)'],
    ['اسم الحصة (يوغا/كارديو)', 'Class name (yoga/cardio)'],
    ['اليوم (الأحد…)', 'Day (Sunday...)'],
    ['نادي jaola', 'jaola Gym'],
    ['حصة جماعية أسبوعياً', 'A weekly group class'],
    ['دخول غير محدود', 'Unlimited access'],
    ['حصص جماعية', 'Group classes'],
    ['خصم على المكمّلات', 'Discount on supplements'],
    ['مدرّب شخصي', 'Personal trainer'],
    ['خزانة خاصة', 'Private locker'],
    ['تقييم لياقة', 'Fitness assessment'],
    ['يوغا الصباح', 'Morning yoga'],
    ['ربع سنوي', 'Quarterly'],
    ['سنوي VIP', 'Yearly VIP'],
    ['اشترك الآن', 'Subscribe now'],
    ['لا باقات حالياً.', 'No plans now.'],
    ['الاسم الكامل', 'Full name'],
    ['اكتب الاسم والهاتف', 'Enter name and phone'],
    ['تم الاشتراك', 'Subscribed'],
    ['بطاقة عضوية', 'Membership card'],
    ['بطاقة العضوية', 'Membership card'],
    ['أهلاً بك في العائلة', 'Welcome to the family'],
    ['احجز مقعدك', 'Book your seat'],
    ['لا حصص مجدولة.', 'No classes scheduled.'],
    ['اشترك أولاً لتحجز حصة', 'Subscribe first to book a class'],
    ['الحصة ممتلئة', 'Class is full'],
    ['محجوزة لديك بالفعل', 'Already booked by you'],
    ['حُجز مقعدك في', 'Booked your seat in'],
    ['لا أعضاء بعد — اشترك من صفحة الباقات.', 'No members yet — subscribe from the plans page.'],
    ['إيراد الاشتراكات', 'Subscriptions revenue'],
    ['لا أعضاء بعد.', 'No members yet.'],
    ['اكتب اسم الباقة', 'Enter plan name'],
    ['أُضيفت الباقة', 'Plan added'],
    ['اكتب اسم الحصة', 'Enter class name'],
    ['أُضيفت الحصة', 'Class added'],
    ['نادٍ رياضي', 'Gym'],
    ['موقع نادي', 'Gym site'],
    ['اشترك', 'Subscribe'],
    ['الاشتراك', 'Signup'],
    ['الباقات', 'Plans'],
    ['الباقة', 'Plan'],
    ['باقة', 'plan'],
    ['المدرّب', 'Coach'],
    ['مدرّب', 'Coach'],
    ['السعة', 'Capacity'],
    ['ممتلئة', 'Full'],
    ['الحصص', 'Classes'],
    ['الحصة', 'Class'],
    ['حصة', 'class'],
    ['الأعضاء', 'Members'],
    ['العضو', 'Member'],
    ['البداية', 'Start'],
    ['النهاية', 'End'],
    ['ينتهي', 'Ends'],
    ['يوغا', 'Yoga'],
    ['كارديو', 'Cardio'],
    ['حديد', 'Weights'],
    ['سارة', 'Sara'],
    ['خالد', 'Khalid'],
    ['ماجد', 'Majed'],
    ['الأحد', 'Sunday'],
    ['الاثنين', 'Monday'],
    ['الأربعاء', 'Wednesday'],
    ['خدمة', 'service'],
    ['قطعة', 'part'],
    ['ر.س', 'SAR'],
    ['المرحلة التالية', 'Next stage'],
    ['استقبال', 'Reception'],
    ['فاتورة', 'Invoice'],
    ['عميل', 'Customer'],
    ['ر.س', 'SAR'],
    // ── 📒 accounting / 💇 salon ──
    ['دليل حسابات · قيود يومية متوازنة · دفتر أستاذ · ميزان مراجعة · قائمة دخل.', 'Chart of accounts · Balanced journal entries · Ledger · Trial balance · Income statement.'],
    ['خدمات احترافية · فريق ماهر · حجز في دقيقة.', 'Professional services · Skilled team · Book in a minute.'],
    ['نظام المحاسبة', 'Accounting System'],
    ['دليل الحسابات', 'Chart of accounts'],
    ['اسم الحساب', 'Account name'],
    ['حقوق ملكية', 'Equity'],
    ['قيد يومية', 'Journal entry'],
    ['بيان القيد', 'Entry description'],
    ['ترحيل القيد', 'Post entry'],
    ['القيود المرحّلة', 'Posted entries'],
    ['دفتر الأستاذ', 'General ledger'],
    ['ميزان المراجعة', 'Trial balance'],
    ['لوحة مالية', 'Financial dashboard'],
    ['آخر القيود', 'Recent entries'],
    ['العملاء (مدينون)', 'Customers (receivable)'],
    ['الموردون (دائنون)', 'Suppliers (payable)'],
    ['رأس المال', 'Capital'],
    ['المصروفات', 'Expenses'],
    ['المبيعات', 'Sales'],
    ['الصندوق', 'Cash'],
    ['البنك', 'Bank'],
    ['إجمالي الأصول', 'Total assets'],
    ['صافي الربح', 'Net profit'],
    ['صافي الدخل', 'Net income'],
    ['توازن الميزان', 'Balance check'],
    ['متوازن ✅', 'Balanced ✅'],
    ['خلل ❌', 'Off ❌'],
    ['لا قيود بعد.', 'No entries yet.'],
    ['لا حسابات بعد.', 'No accounts yet.'],
    ['اكتب اسم الحساب', 'Enter account name'],
    ['أُضيف الحساب', 'Account added'],
    ['لا يمكن حذف حساب له قيود', 'Cannot delete an account with entries'],
    ['لا قيود مرحّلة بعد.', 'No posted entries yet.'],
    ['غير متوازن: فرق', 'Unbalanced: difference'],
    ['غير متوازن', 'Unbalanced'],
    ['متوازن', 'Balanced'],
    ['اختر الحساب وأدخل مبلغاً في مدين أو دائن', 'Pick an account and enter an amount in debit or credit'],
    ['السطر إمّا مدين أو دائن — لا الاثنين', 'A line is either debit or credit, not both'],
    ['القيد يحتاج سطرين على الأقل', 'Entry needs at least two lines'],
    ['القيد غير متوازن — مدين يجب أن يساوي دائن', 'Entry is unbalanced — debit must equal credit'],
    ['رُحّل القيد', 'Entry posted'],
    ['لا حركات على هذا الحساب.', 'No transactions on this account.'],
    ['لا أرصدة بعد.', 'No balances yet.'],
    ['صُدّر الميزان CSV', 'Trial balance exported to CSV'],
    ['المدير المالي', 'CFO'],
    ['مدير مالي', 'CFO'],
    ['أصول', 'Assets'],
    ['خصوم', 'Liabilities'],
    ['إيراد', 'Revenue'],
    ['مصروف', 'Expense'],
    ['حساب', 'Account'],
    ['الحسابات', 'Accounts'],
    ['الحساب', 'Account'],
    ['القيود', 'Entries'],
    ['الأستاذ', 'Ledger'],
    ['الميزان', 'Trial balance'],
    ['الرصيد', 'Balance'],
    ['مدين', 'Debit'],
    ['دائن', 'Credit'],
    ['سطراً', 'line'],
    ['الأسطر', 'lines'],
    ['القيمة', 'Value'],
    ['فرق', 'diff'],
    ['قيد', 'Entry'],
    ['سطر', 'line'],
    ['البيان', 'Description'],
    ['الإيرادات', 'Revenues'],
    ['إطلالتك تبدأ من هنا', 'Your look starts here'],
    ['صالون تجميل', 'Beauty Salon'],
    ['اسم الخدمة', 'Service name'],
    ['المدة (دقيقة)', 'Duration (minutes)'],
    ['اسم الأخصائي', 'Specialist name'],
    ['التخصص (حلاقة/مكياج)', 'Specialty (hair/makeup)'],
    ['إضافة عضو فريق', 'Add team member'],
    ['مواعيد اليوم فأكثر', 'Today and upcoming'],
    ['قص شعر', 'Haircut'],
    ['صبغة', 'Coloring'],
    ['مكياج', 'Makeup'],
    ['عناية بالبشرة', 'Skincare'],
    ['مصفّفة شعر', 'Hair stylist'],
    ['خبيرة مكياج', 'Makeup artist'],
    ['احجز الآن', 'Book now'],
    ['لا خدمات حالياً.', 'No services now.'],
    ['اكتب اسمك وهاتفك', 'Enter your name and phone'],
    ['هذا الوقت محجوز لدى الأخصائي — اختر وقتاً آخر', 'This time is taken for the specialist — pick another time'],
    ['تم الحجز', 'Booked'],
    ['في انتظارك', 'See you soon'],
    ['لا مواعيد بعد — احجز من صفحة الخدمات.', 'No appointments yet — book from the services page.'],
    ['إيراد متوقّع', 'Expected revenue'],
    ['لا مواعيد قادمة.', 'No upcoming appointments.'],
    ['اكتب اسم الخدمة', 'Enter service name'],
    ['أُضيفت الخدمة', 'Service added'],
    ['اكتب اسم الأخصائي', 'Enter specialist name'],
    ['أُضيف عضو الفريق', 'Team member added'],
    ['أُلغي الموعد', 'Appointment cancelled'],
    ['موقع صالون', 'Salon site'],
    ['خدماتنا', 'Our services'],
    ['الأخصائي', 'Specialist'],
    ['أخصائي', 'Specialist'],
    ['الخدمة', 'Service'],
    ['خدمة', 'Service'],
    ['التخصص', 'Specialty'],
    ['المدة', 'Duration'],
    ['ليلى', 'Layla'],
    ['نورة', 'Noura'],
    ['صالون', 'Salon'],
    ['حلاقة', 'Barber'],
    ['ر.س', 'SAR'],

    // ── المستودع (jaola-warehouse) ─────────────────────────────────
    ['نظام إدارة المستودع', 'Warehouse Management System'],
    ['مستودع jaola', 'jaola Warehouse'],
    ['أصناف ومواقع · شحنات واردة وصادرة · تحويل بين مواقع · تقارير حركة.', 'Items & locations · inbound/outbound shipments · transfer between locations · movement reports.'],
    ['مدير مستودع', 'Warehouse manager'],
    ['مشغّل', 'Operator'],
    ['تجريبياً: كلمة المرور «admin».', 'Demo: password is admin.'],
    ['أصناف تحت الحد الأدنى', 'Items below minimum'],
    ['الأصناف والمواقع', 'Items & Locations'],
    ['موقع التخزين (رف A1)', 'Storage location (Shelf A1)'],
    ['الكمية الابتدائية', 'Initial quantity'],
    ['الحد الأدنى', 'Minimum'],
    ['وارد (استلام شحنة)', 'Inbound (receive shipment)'],
    ['مرجع الشحنة/المورّد', 'Shipment/supplier reference'],
    ['استلام الشحنة', 'Receive shipment'],
    ['صادر (صرف شحنة)', 'Outbound (dispense shipment)'],
    ['مرجع الطلب/الجهة', 'Order/party reference'],
    ['صرف الشحنة', 'Dispense shipment'],
    ['سجل الشحنات', 'Shipment log'],
    ['الشحنات CSV', 'Shipments CSV'],
    ['حركة آخر ٧ أيام (وارد مقابل صادر)', 'Movement — last 7 days (inbound vs outbound)'],
    ['اسم المستودع', 'Warehouse name'],

    // ── الفندق (jaola-hotel) ────────────────────────────────────────
    ['فندق jaola', 'jaola Hotel'],
    ['إقامة تستحقها', 'A stay you deserve'],
    ['غرف مريحة · إطلالات رائعة · حجز فوري بتأكيد لحظي.', 'Comfortable rooms · great views · instant booking with instant confirmation.'],
    ['أنواع الغرف', 'Room Types'],
    ['إتمام الحجز', 'Complete Booking'],
    ['تاريخ الوصول', 'Check-in date'],
    ['تاريخ المغادرة', 'Check-out date'],
    ['اسم النزيل', 'Guest name'],
    ['نوع الغرفة', 'Room type'],
    ['غرفة قياسية', 'Standard room'],
    ['سرير مزدوج، إطلالة على الحديقة', 'Double bed, garden view'],
    ['غرفة ديلوكس', 'Deluxe room'],
    ['مساحة أوسع، إطلالة بحرية', 'More space, sea view'],
    ['جناح عائلي', 'Family suite'],
    ['غرفتان متصلتان، صالة صغيرة', 'Two connected rooms, small lounge'],
    ['اكتب اسم نوع الغرفة', 'Enter room type name'],
    ['أُضيف نوع الغرفة', 'Room type added'],
    ['عدد الليالي', 'Nights'],
    ['تأكيد حجز', 'Booking confirmation'],
    ['النزيل', 'Guest'],
    ['الوصول', 'Check-in'],
    ['المغادرة', 'Check-out'],
    ['بانتظار إقامتك', 'Looking forward to your stay'],
    ['لا حجوزات بعد — احجز من صفحة الغرف.', 'No reservations yet — book from the rooms page.'],
    ['تأكيد الحجز', 'Booking confirmation'],
    ['تاريخ المغادرة يجب أن يكون بعد الوصول.', 'Check-out date must be after check-in.'],
    ['لا تتوفر غرف من هذا النوع في هذا المدى — جرّب تواريخ أخرى.', 'No rooms of this type available for this range — try other dates.'],
    ['اكتب الاسم والهاتف.', 'Enter the name and phone.'],
    ['تم تأكيد الحجز', 'Booking confirmed'],
    ['اختر تاريخ الوصول والمغادرة.', 'Choose check-in and check-out dates.'],
    ['أنواع غرف', 'Room types'],
    ['إجمالي الغرف', 'Total rooms'],
    ['إيراد الحجوزات', 'Booking revenue'],
    ['اسم نوع الغرفة', 'Room type name'],
    ['السعر لليلة', 'Price per night'],
    ['عدد الغرف', 'Room count'],
    ['سعة النزلاء', 'Guest capacity'],
    ['نزيل', 'Guest'],
    ['إضافة نوع غرفة', 'Add room type'],

    // ── المغسلة (jaola-laundry) ────────────────────────────────────
    ['نظام إدارة مغسلة', 'Laundry Management System'],
    ['مغسلة jaola', 'jaola Laundry'],
    ['طلبات غسيل بقطع متعددة · تتبّع حالة الطلب · إيصالات قابلة للطباعة · تقرير إيرادات.', 'Multi-item laundry orders · order status tracking · printable receipts · revenue report.'],
    ['مشغّل مغسلة', 'Laundry operator'],
    ['🔔 طلبات جاهزة للاستلام', '🔔 Orders ready for pickup'],
    ['طلب غسيل جديد', 'New laundry order'],
    ['إنشاء الطلب وطباعة الإيصال', 'Create order and print receipt'],
    ['كتالوج القطع', 'Garment Catalog'],
    ['اسم الصنف (قميص/بنطلون...)', 'Item name (shirt/pants...)'],
    ['اسم المغسلة', 'Laundry name'],

    // ── تأجير السيارات (jaola-carrental) ────────────────────────────
    ['تأجير سيارات jaola', 'jaola Car Rental'],
    ['استأجر سيارتك بضغطة زر', 'Rent your car with one click'],
    ['أسطول متنوّع · أسعار يومية واضحة · حجز فوري بتأكيد لحظي.', 'Diverse fleet · clear daily rates · instant booking with instant confirmation.'],
    ['فئات السيارات', 'Car Categories'],
    ['→ السيارات', '→ Cars'],
    ['تاريخ الاستلام', 'Pickup date'],
    ['تاريخ التسليم', 'Return date'],
    ['اسم/فئة السيارة', 'Car name/category'],
    ['السعر لليوم', 'Price per day'],
    ['عدد السيارات', 'Number of cars'],
    ['إضافة فئة سيارة', 'Add car category'],
];

// بالأطول أولاً — يمنع أن تأكل الترجمة القصيرة جزءاً من سلسلة أطول
const ORDERED = [...DICT].sort((a, b) => b[0].length - a[0].length);

/** يترجم نصاً واحداً (HTML أو JS) بالقاموس الحتمي. */
export function localizeText(text = '') {
    let out = text;
    for (const [ar, en] of ORDERED) out = out.split(ar).join(en);
    return out;
}

/** نسبة العربية المتبقية بعد التوطين (لقياس التغطية في الاختبارات). */
export function arabicRatio(text = '') {
    const ar = (text.match(/[؀-ۿ]/g) || []).length;
    return text.length ? ar / text.length : 0;
}

/**
 * 🧩 المدخل الرئيسي: يوطّن ملفات قالب كاملة حسب اللغة.
 * - lang !== 'en' → تُعاد الملفات كما هي (العربية هي الأصل).
 * - index.html: قلب lang/dir + ترجمة القاموس.
 * - *.js: ترجمة القاموس (سلاسل عربية فقط — الكود لا يُمسّ).
 * - *.css: يُلحق تصحيح توسيط الـ toast للاتجاه الجديد.
 */
export function localizeTemplateFiles(files = [], lang = 'ar') {
    if (lang !== 'en') return files;
    return files.map(f => {
        if (f.name.endsWith('.html')) {
            let html = localizeText(f.content)
                .replace(/lang="ar"/g, 'lang="en"')
                .replace(/dir="rtl"/g, 'dir="ltr"');
            return { ...f, content: html };
        }
        if (f.name.endsWith('.js')) {
            return { ...f, content: localizeText(f.content) };
        }
        if (f.name.endsWith('.css')) {
            // toast كان يفترض RTL (translateX(50%)) — في LTR يلزم -50%
            return { ...f, content: f.content + '\nhtml[dir=ltr] .toast{transform:translateX(-50%)}\n' };
        }
        return f;
    });
}
